# group_vars/slurm_cluster.yml
---
# Переменные для всего Slurm кластера (БЕЗ ХАРДКОДА)

# =============================================================================
# КЛАСТЕР НАСТРОЙКИ  
# =============================================================================

slurm_cluster_name: "hpc-cluster"
timezone: "Europe/Moscow"

# =============================================================================
# NFS НАСТРОЙКИ (АВТООПРЕДЕЛЕНИЕ)
# =============================================================================

# NFS сервер автоматически определится как первый в группе slurm_master
# nfs_server: "{{ groups['slurm_master'][0] }}"

# NFS экспорты автоматически создадутся для всех узлов в nfs_client группе
nfs_export_options: "rw,sync,no_root_squash"
nfs_mount_options: "defaults,_netdev"

# =============================================================================
# SLURM НАСТРОЙКИ
# =============================================================================

slurm_user: "slurm"
slurm_group: "slurm"
slurm_debug_level: "3"

# =============================================================================
# ПРИМЕР ПЕРЕОПРЕДЕЛЕНИЯ ЧЕРЕЗ INVENTORY
# =============================================================================

# Если нужно переопределить для конкретного окружения,
# можно сделать так в inventory:
#
# [slurm_cluster:vars]
# timezone=UTC
# slurm_cluster_name=prod-hpc-cluster
# nfs_export_options=rw,sync,no_root_squash,no_subtree_check
#
# Или создать отдельные group_vars для разных окружений:
# group_vars/prod/slurm_cluster.yml
# group_vars/dev/slurm_cluster.yml
# group_vars/test/slurm_cluster.yml