---
- name: "Add node to existing Slurm cluster"
  hosts: "{{ target_node | default('cn54') }}"
  become: true
  gather_facts: true
  roles:
    - slurm_node_recovery

- name: "Resume node on master"
  hosts: master_nodes
  become: true
  tasks:
    - name: "Wait for node to be ready"
      wait_for:
        port: 6818
        host: "{{ target_node | default('cn54') }}"
        timeout: 60

    - name: "Resume node in Slurm"
      command: scontrol update NodeName={{ target_node | default('cn54') }} State=RESUME
      ignore_errors: yes

    - name: "Check final node status"
      shell: scontrol show node {{ target_node | default('cn54') }}
      register: final_status

    - name: "Display final status"
      debug:
        var: final_status.stdout_lines