# roles/grub_apparmor/tasks/main.yml
---
# Роль: grub_apparmor - отключение AppArmor для контейнеров

- name: "[GRUB] Проверка наличия apparmor=0"
  shell: grep -q 'apparmor=0' /etc/default/grub
  register: apparmor_present
  failed_when: false
  changed_when: false

- name: "[GRUB] Добавление apparmor=0 к GRUB параметрам"
  replace:
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT="[^"]*)"$'
    replace: '\1 apparmor=0"'
    backup: yes
  when: apparmor_present.rc != 0
  notify: 
    - update grub
    - reboot system

- name: "[GRUB] Исправление дублирования apparmor=0"
  replace:
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT="[^"]*) apparmor=0 apparmor=0"$'
    replace: '\1 apparmor=0"'