https://arxiv.org/html/2508.01989v1


Отлично! Настроение боевое — две недели пробивались через эту стену, и вот оно работает.
Запрос с метриками:
bashcurl -s http://10.99.91.39:8000/generate \
  -H "Content-Type: application/json" \
  -d '{
    "text": "Explain the theory of relativity in detail",
    "sampling_params": {
      "max_new_tokens": 200,
      "temperature": 0.7
    }
  }'
После ответа посмотри метрики напрямую с серверов:
bash# Prefill throughput
curl -s http://10.99.91.39:30000/get_server_info | python3 -m json.tool

# Decode throughput  
curl -s http://10.99.91.49:30001/get_server_info | python3 -m json.tool
Для нагрузочного теста (чтобы видеть реальную пропускную способность):
bashpython3 -m sglang.bench_serving \
  --backend sglang \
  --host 10.99.91.39 \
  --port 8000 \
  --num-prompts 20 \
  --request-rate 4 \
  --input-len 512 \
  --output-len 128
Присылай результаты — посмотрим TTFT (time to first token) и throughput. Для схемы 2P+2D с DeepSeek-R1 на H100 ожидаем TTFT < 500ms и decode > 1000 tok/s суммарно.


1
source /app/sglang/sglang-latest/bin/activate
SGLANG_HOST_IP=10.99.91.39 MC_GID_INDEX=3 MC_TCP_BIND_ADDRESS=10.99.91.39 SGLANG_LOCAL_IP_NIC=ens108np0 GLOO_SOCKET_FAMILY=AF_INET GLOO_SOCKET_IFNAME=ens108np0 NCCL_SOCKET_IFNAME=ens108np0 NCCL_IB_HCA=mlx5_0,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_9,mlx5_10,mlx5_11 NCCL_IB_GID_INDEX=3 NCCL_IB_TC=106 NCCL_IB_DISABLE=0 NCCL_NET_GDR_LEVEL=PIX NCCL_NVLS_ENABLE=0 NCCL_CROSS_NIC=1 NCCL_TIMEOUT=600 CUDA_DEVICE_MAX_CONNECTIONS=1 PYTORCH_ALLOC_CONF=expandable_segments:True,max_split_size_mb:256 TOKENIZERS_PARALLELISM=false /opt/mooncake-libs/run-with-new-libstdc.sh python3 -m sglang.launch_server   --model-path /app/models/Deepseek-R1/   --trust-remote-code   --tp-size 16   --host 10.99.91.39   --port 30000   --dist-init-addr 10.99.91.39:5000   --nnodes 2   --node-rank 0   --mem-fraction-static 0.8   --disaggregation-mode prefill   --disaggregation-transfer-backend nixl   --disaggregation-ib-device mlx5_0,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_9,mlx5_10,mlx5_11   --disaggregation-bootstrap-port 8998   --disable-cuda-graph


2
SGLANG_HOST_IP=10.99.91.41 MC_GID_INDEX=3 MC_TCP_BIND_ADDRESS=10.99.91.41 SGLANG_LOCAL_IP_NIC=ens108np0 GLOO_SOCKET_FAMILY=AF_INET GLOO_SOCKET_IFNAME=ens108np0 NCCL_SOCKET_IFNAME=ens108np0 NCCL_IB_HCA=mlx5_0,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_9,mlx5_10,mlx5_11 NCCL_IB_GID_INDEX=3 NCCL_IB_TC=106 NCCL_IB_DISABLE=0 NCCL_NET_GDR_LEVEL=PIX NCCL_NVLS_ENABLE=0 NCCL_CROSS_NIC=1 NCCL_TIMEOUT=600 CUDA_DEVICE_MAX_CONNECTIONS=1 PYTORCH_ALLOC_CONF=expandable_segments:True,max_split_size_mb:256 TOKENIZERS_PARALLELISM=false /opt/mooncake-libs/run-with-new-libstdc.sh python3 -m sglang.launch_server   --model-path /app/models/Deepseek-R1/   --trust-remote-code   --tp-size 16   --host 10.99.91.41   --port 30000   --dist-init-addr 10.99.91.39:5000   --nnodes 2   --node-rank 1   --mem-fraction-static 0.8   --disaggregation-mode prefill   --disaggregation-transfer-backend nixl   --disaggregation-ib-device mlx5_0,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_9,mlx5_10,mlx5_11   --disaggregation-bootstrap-port 8998   --disable-cuda-graph

3
SGLANG_HOST_IP=10.99.91.49 MC_GID_INDEX=3 MC_TCP_BIND_ADDRESS=10.99.91.49 SGLANG_LOCAL_IP_NIC=ens3np0 GLOO_SOCKET_FAMILY=AF_INET GLOO_SOCKET_IFNAME=ens3np0 NCCL_SOCKET_IFNAME=ens3np0 NCCL_IB_HCA=mlx5_0,mlx5_1,mlx5_2,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_7 NCCL_IB_GID_INDEX=3 NCCL_IB_TC=106 NCCL_IB_DISABLE=0 NCCL_NET_GDR_LEVEL=PIX NCCL_NVLS_ENABLE=0 NCCL_CROSS_NIC=1 NCCL_TIMEOUT=600 CUDA_DEVICE_MAX_CONNECTIONS=1 PYTORCH_ALLOC_CONF=expandable_segments:True,max_split_size_mb:256 TOKENIZERS_PARALLELISM=false /opt/mooncake-libs/run-with-new-libstdc.sh python3 -m sglang.launch_server   --model-path /app/models/Deepseek-R1/   --trust-remote-code   --tp-size 16   --host 10.99.91.49   --port 30001   --dist-init-addr 10.99.91.49:5000   --nnodes 2   --node-rank 0   --mem-fraction-static 0.8   --disaggregation-mode decode   --disaggregation-transfer-backend nixl   --disaggregation-ib-device mlx5_0,mlx5_1,mlx5_2,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_7   --max-running-requests 128

6
SGLANG_HOST_IP=10.99.91.35 MC_GID_INDEX=3 MC_TCP_BIND_ADDRESS=10.99.91.35 SGLANG_LOCAL_IP_NIC=ens3np0 GLOO_SOCKET_FAMILY=AF_INET GLOO_SOCKET_IFNAME=ens3np0 NCCL_SOCKET_IFNAME=ens3np0 NCCL_IB_HCA=mlx5_0,mlx5_1,mlx5_2,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_7 NCCL_IB_GID_INDEX=3 NCCL_IB_TC=106 NCCL_IB_DISABLE=0 NCCL_NET_GDR_LEVEL=PIX NCCL_NVLS_ENABLE=0 NCCL_CROSS_NIC=1 NCCL_TIMEOUT=600 CUDA_DEVICE_MAX_CONNECTIONS=1 PYTORCH_ALLOC_CONF=expandable_segments:True,max_split_size_mb:256 TOKENIZERS_PARALLELISM=false /opt/mooncake-libs/run-with-new-libstdc.sh python3 -m sglang.launch_server   --model-path /app/models/Deepseek-R1/   --trust-remote-code   --tp-size 16   --host 10.99.91.35   --port 30001   --dist-init-addr 10.99.91.49:5000   --nnodes 2   --node-rank 1   --mem-fraction-static 0.8   --disaggregation-mode decode   --disaggregation-transfer-backend nixl   --disaggregation-ib-device mlx5_0,mlx5_1,mlx5_2,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_7   --max-running-requests 128

router
((sglang-0.5.9) ) [dcbsr_dev@tpgds-aihub0001 ~]$   /app/sglang/sglang-latest/bin/python3 -m sglang_router.launch_router   --pd-disaggregation   --prefill http://10.99.91.39:30000 8998   --decode http://10.99.91.49:30001   --host 0.0.0.0   --port 8000




[dcbsr_dev@tpgds-aihub0003 ~]$ curl -s http://10.99.91.39:8000/generate \
  -H "Content-Type: application/json" \
  -d '{
    "text": "Explain the theory of relativity in detail",
    "sampling_params": {
      "max_new_tokens": 200,
      "temperature": 0.7
    }
  }'
{"text":".\n\nAnswer\n\n0 (0 stars)\n\n0\n\ndontknowit23 2 years ago\n51 response - 0 helps \nAnswer:\n\nThe theory of relativity usually encompasses two interrelated theories by Albert Einstein: special relativity and general relativity. Special relativity applies to all physical phenomena in the absence of gravity. General relativity explains the law of gravitation and its relation to other forces of nature.It applies to the cosmological and astrophysical realm, including astronomy. The theory transformed theoretical physics and astronomy during the 20th century, superseding a 200-year-old theory of mechanics created primarily by Isaac Newton. It introduced concepts including spacetime as a unified entity of space and time, relativity of simultaneity, kinematic and gravitational time dilation, and length contraction. In the field of physics, relativity improved the science of elementary particles and their fundamental interactions, along with ushering in the nuclear age. With relativity, cosmology and astrophysics predicted extraordinary astronomical phenomena such as neutron stars, black holes, and gravitational waves.\n\nExplanation","output_ids":[339,7805,271,18,343,18,12570,868,18,271,70,1039,33944,279,1349,223,20,1737,5084,201,4287,4256,565,223,18,7531,539,7805,979,671,6129,294,76407,5292,44995,1234,105467,17800,513,26218,43490,28,3953,76407,305,3810,76407,16,11609,76407,19338,304,710,5131,25298,295,270,13651,294,22927,16,7120,76407,16428,270,2950,294,13846,4458,305,1009,9960,304,915,8753,294,4936,52402,19338,304,270,102897,305,110997,18000,23285,14,2622,59910,16,455,6129,23785,16242,18771,305,59910,2184,270,223,397,463,6683,14,52365,10511,260,223,792,6680,11489,6129,294,29821,5572,12515,513,39769,26037,16,983,10097,10869,2622,121928,412,260,41626,16090,294,3987,305,1014,14,76407,294,15261,114811,14,105116,305,43406,1014,103025,14,305,4892,40946,16,660,270,2994,294,18771,14,76407,10103,270,6262,294,23836,12663,305,786,11264,12013,14,3758,418,550,57766,295,270,12613,4109,16,3710,76407,14,117457,305,110997,23501,18888,25335,61004,25298,1345,412,51666,12570,14,5159,21137,14,305,43406,15110,339,28395],"meta_info":{"id":"725ac38f33db458b94f52d8cc40b0ed7","finish_reason":{"type":"length","length":200},"prompt_tokens":8,"weight_version":"default","total_retractions":0,"completion_tokens":200,"ca

ответ префилл 1
[2026-03-02 14:44:10 TP0] Decode batch, #running-req: 1, #token: 33, token usage: 0.00, pre-allocated usage: 0.00, #prealloc-req: 0, #transfer-req: 0, #retracted-req: 0, cuda graph: True, gen throughput (token/s): 0.04, #queue-req: 0
[2026-03-02 14:44:11 TP0] Decode batch, #running-req: 1, #token: 73, token usage: 0.00, pre-allocated usage: 0.00, #prealloc-req: 0, #transfer-req: 0, #retracted-req: 0, cuda graph: True, gen throughput (token/s): 78.20, #queue-req: 0
[2026-03-02 14:44:11 TP0] Decode batch, #running-req: 1, #token: 113, token usage: 0.00, pre-allocated usage: 0.00, #prealloc-req: 0, #transfer-req: 0, #retracted-req: 0, cuda graph: True, gen throughput (token/s): 77.89, #queue-req: 0
[2026-03-02 14:44:12 TP0] Decode batch, #running-req: 1, #token: 153, token usage: 0.00, pre-allocated usage: 0.00, #prealloc-req: 0, #transfer-req: 0, #retracted-req: 0, cuda graph: True, gen throughput (token/s): 77.90, #queue-req: 0
[2026-03-02 14:44:12 TP0] Decode batch, #running-req: 1, #token: 193, token usage: 0.00, pre-allocated usage: 0.00, #prealloc-req: 0, #transfer-req: 0, #retracted-req: 0, cuda graph: True, gen throughput (token/s): 77.90, #queue-req: 0


[dcbsr_dev@tpgds-aihub0003 ~]$ curl -s http://10.99.91.39:30000/get_server_info | python3 -m json.tool
{
    "model_path": "/app/models/Deepseek-R1/",
    "tokenizer_path": "/app/models/Deepseek-R1/",
    "tokenizer_mode": "auto",
    "tokenizer_worker_num": 1,
    "skip_tokenizer_init": false,
    "load_format": "auto",
    "model_loader_extra_config": "{}",
    "trust_remote_code": true,
    "context_length": null,
    "is_embedding": false,
    "enable_multimodal": null,
    "revision": null,
    "model_impl": "auto",
    "host": "10.99.91.39",
    "port": 30000,
    "fastapi_root_path": "",
    "grpc_mode": false,
    "skip_server_warmup": false,
    "warmups": null,
    "nccl_port": null,
    "checkpoint_engine_wait_weights_before_ready": false,
    "dtype": "auto",
    "quantization": null,
    "quantization_param_path": null,
    "kv_cache_dtype": "auto",
    "enable_fp32_lm_head": false,
    "modelopt_quant": null,
    "modelopt_checkpoint_restore_path": null,
    "modelopt_checkpoint_save_path": null,
    "modelopt_export_path": null,
    "quantize_and_serve": false,
    "rl_quant_profile": null,
    "mem_fraction_static": 0.8,
    "max_running_requests": null,
    "max_queued_requests": null,
    "max_total_tokens": null,
    "chunked_prefill_size": 8192,
    "enable_dynamic_chunking": false,
    "max_prefill_tokens": 16384,
    "prefill_max_requests": null,
    "schedule_policy": "fcfs",
    "enable_priority_scheduling": false,
    "abort_on_priority_when_disabled": false,
    "schedule_low_priority_values_first": false,
    "priority_scheduling_preemption_threshold": 10,
    "schedule_conservativeness": 1.0,
    "page_size": 1,
    "swa_full_tokens_ratio": 0.8,
    "disable_hybrid_swa_memory": false,
    "radix_eviction_policy": "lru",
    "enable_prefill_delayer": false,
    "prefill_delayer_max_delay_passes": 30,
    "prefill_delayer_token_usage_low_watermark": null,
    "prefill_delayer_forward_passes_buckets": null,
    "prefill_delayer_wait_seconds_buckets": null,
    "device": "cuda",
    "tp_size": 16,
    "pp_size": 1,
    "pp_max_micro_batch_size": null,
    "pp_async_batch_depth": 0,
    "stream_interval": 1,
    "stream_output": false,
    "random_seed": 128558095,
    "constrained_json_whitespace_pattern": null,
    "constrained_json_disable_any_whitespace": false,
    "watchdog_timeout": 300,
    "soft_watchdog_timeout": null,
    "dist_timeout": null,
    "download_dir": null,
    "model_checksum": null,
    "base_gpu_id": 0,
    "gpu_id_step": 1,
    "sleep_on_idle": false,
    "custom_sigquit_handler": null,
    "log_level": "info",
    "log_level_http": null,
    "log_requests": false,
    "log_requests_level": 2,
    "log_requests_format": "text",
    "log_requests_target": null,
    "uvicorn_access_log_exclude_prefixes": [],
    "crash_dump_folder": null,
    "show_time_cost": false,
    "enable_metrics": false,
    "enable_metrics_for_all_schedulers": false,
    "tokenizer_metrics_custom_labels_header": "x-custom-labels",
    "tokenizer_metrics_allowed_custom_labels": null,
    "extra_metric_labels": null,
    "bucket_time_to_first_token": null,
    "bucket_inter_token_latency": null,
    "bucket_e2e_request_latency": null,
    "collect_tokens_histogram": false,
    "prompt_tokens_buckets": null,
    "generation_tokens_buckets": null,
    "gc_warning_threshold_secs": 0.0,
    "decode_log_interval": 40,
    "enable_request_time_stats_logging": false,
    "kv_events_config": null,
    "enable_trace": false,
    "otlp_traces_endpoint": "localhost:4317",
    "export_metrics_to_file": false,
    "export_metrics_to_file_dir": null,
    "api_key": null,
    "admin_api_key": null,
    "served_model_name": "/app/models/Deepseek-R1/",
    "weight_version": "default",
    "chat_template": null,
    "hf_chat_template_name": null,
    "completion_template": null,
    "file_storage_path": "sglang_storage",
    "enable_cache_report": false,
    "reasoning_parser": null,
    "tool_call_parser": null,
    "tool_server": null,
    "sampling_defaults": "model",
    "dp_size": 1,
    "load_balance_method": "follow_bootstrap_room",
    "attn_cp_size": 1,
    "moe_dp_size": 1,
    "dist_init_addr": "10.99.91.39:5000",
    "nnodes": 2,
    "node_rank": 0,
    "json_model_override_args": "{}",
    "preferred_sampling_params": null,
    "enable_lora": null,
    "enable_lora_overlap_loading": null,
    "max_lora_rank": null,
    "lora_target_modules": null,
    "lora_paths": null,
    "max_loaded_loras": null,
    "max_loras_per_batch": 8,
    "lora_eviction_policy": "lru",
    "lora_backend": "csgmv",
    "max_lora_chunk_size": 16,
    "attention_backend": "fa3",
    "decode_attention_backend": null,
    "prefill_attention_backend": null,
    "sampling_backend": "flashinfer",
    "grammar_backend": "xgrammar",
    "mm_attention_backend": null,
    "fp8_gemm_runner_backend": "auto",
    "fp4_gemm_runner_backend": "flashinfer_cutlass",
    "nsa_prefill_backend": null,
    "nsa_decode_backend": null,
    "disable_flashinfer_autotune": false,
    "mamba_backend": "triton",
    "speculative_algorithm": null,
    "speculative_draft_model_path": null,
    "speculative_draft_model_revision": null,
    "speculative_draft_load_format": null,
    "speculative_num_steps": null,
    "speculative_eagle_topk": null,
    "speculative_num_draft_tokens": null,
    "speculative_accept_threshold_single": 1.0,
    "speculative_accept_threshold_acc": 1.0,
    "speculative_token_map": null,
    "speculative_attention_mode": "prefill",
    "speculative_draft_attention_backend": null,
    "speculative_moe_runner_backend": "auto",
    "speculative_moe_a2a_backend": null,
    "speculative_draft_model_quantization": null,
    "speculative_ngram_min_match_window_size": 1,
    "speculative_ngram_max_match_window_size": 12,
    "speculative_ngram_min_bfs_breadth": 1,
    "speculative_ngram_max_bfs_breadth": 10,
    "speculative_ngram_match_type": "BFS",
    "speculative_ngram_branch_length": 18,
    "speculative_ngram_capacity": 10000000,
    "enable_multi_layer_eagle": false,
    "ep_size": 1,
    "moe_a2a_backend": "none",
    "moe_runner_backend": "auto",
    "flashinfer_mxfp4_moe_precision": "default",
    "enable_flashinfer_allreduce_fusion": false,
    "deepep_mode": "auto",
    "ep_num_redundant_experts": 0,
    "ep_dispatch_algorithm": null,
    "init_expert_location": "trivial",
    "enable_eplb": false,
    "eplb_algorithm": "auto",
    "eplb_rebalance_num_iterations": 1000,
    "eplb_rebalance_layers_per_chunk": null,
    "eplb_min_rebalancing_utilization_threshold": 1.0,
    "expert_distribution_recorder_mode": null,
    "expert_distribution_recorder_buffer_size": 1000,
    "enable_expert_distribution_metrics": false,
    "deepep_config": null,
    "moe_dense_tp_size": null,
    "elastic_ep_backend": null,
    "mooncake_ib_device": null,
    "max_mamba_cache_size": null,
    "mamba_ssm_dtype": null,
    "mamba_full_memory_ratio": 0.9,
    "mamba_scheduler_strategy": "no_buffer",
    "mamba_track_interval": 256,
    "enable_hierarchical_cache": false,
    "hicache_ratio": 2.0,
    "hicache_size": 0,
    "hicache_write_policy": "write_through",
    "hicache_io_backend": "kernel",
    "hicache_mem_layout": "layer_first",
    "disable_hicache_numa_detect": false,
    "hicache_storage_backend": null,
    "hicache_storage_prefetch_policy": "best_effort",
    "hicache_storage_backend_extra_config": null,
    "hierarchical_sparse_attention_extra_config": null,
    "enable_lmcache": false,
    "kt_weight_path": null,
    "kt_method": "AMXINT4",
    "kt_cpuinfer": null,
    "kt_threadpool_count": 2,
    "kt_num_gpu_experts": null,
    "kt_max_deferred_experts_per_token": null,
    "dllm_algorithm": null,
    "dllm_algorithm_config": null,
    "enable_double_sparsity": false,
    "ds_channel_config_path": null,
    "ds_heavy_channel_num": 32,
    "ds_heavy_token_num": 256,
    "ds_heavy_channel_type": "qk",
    "ds_sparse_decode_threshold": 4096,
    "cpu_offload_gb": 0,
    "offload_group_size": -1,
    "offload_num_in_group": 1,
    "offload_prefetch_step": 1,
    "offload_mode": "cpu",
    "multi_item_scoring_delimiter": null,
    "disable_radix_cache": false,
    "cuda_graph_max_bs": 512,
    "cuda_graph_bs": [
        1,
        2,
        4,
        8,
        12,
        16,
        24,
        32,
        40,
        48,
        56,
        64,
        72,
        80,
        88,
        96,
        104,
        112,
        120,
        128,
        136,
        144,
        152,
        160,
        168,
        176,
        184,
        192,
        200,
        208,
        216,
        224,
        232,
        240,
        248,
        256,
        272,
        288,
        304,
        320,
        336,
        352,
        368,
        384,
        400,
        416,
        432,
        448,
        464,
        480,
        496,
        512
    ],
    "disable_cuda_graph": true,
    "disable_cuda_graph_padding": false,
    "enable_profile_cuda_graph": false,
    "enable_cudagraph_gc": false,
    "enable_layerwise_nvtx_marker": false,
    "enable_nccl_nvls": false,
    "enable_symm_mem": false,
    "disable_flashinfer_cutlass_moe_fp4_allgather": false,
    "enable_tokenizer_batch_encode": false,
    "disable_tokenizer_batch_decode": false,
    "disable_outlines_disk_cache": false,
    "disable_custom_all_reduce": false,
    "enable_mscclpp": false,
    "enable_torch_symm_mem": false,
    "disable_overlap_schedule": false,
    "enable_mixed_chunk": false,
    "enable_dp_attention": false,
    "enable_dp_lm_head": false,
    "enable_two_batch_overlap": false,
    "enable_single_batch_overlap": false,
    "tbo_token_distribution_threshold": 0.48,
    "enable_torch_compile": false,
    "enable_piecewise_cuda_graph": false,
    "enable_torch_compile_debug_mode": false,
    "torch_compile_max_bs": 32,
    "piecewise_cuda_graph_max_tokens": 2048,
    "piecewise_cuda_graph_tokens": [
        4,
        8,
        12,
        16,
        20,
        24,
        28,
        32,
        48,
        64,
        80,
        96,
        112,
        128,
        144,
        160,
        176,
        192,
        208,
        224,
        240,
        256,
        288,
        320,
        352,
        384,
        416,
        448,
        480,
        512,
        576,
        640,
        704,
        768,
        832,
        896,
        960,
        1024,
        1280,
        1536,
        1792,
        2048
    ],
    "piecewise_cuda_graph_compiler": "eager",
    "torchao_config": "",
    "enable_nan_detection": false,
    "enable_p2p_check": false,
    "triton_attention_reduce_in_fp32": false,
    "triton_attention_num_kv_splits": 8,
    "triton_attention_split_tile_size": null,
    "num_continuous_decode_steps": 1,
    "delete_ckpt_after_loading": false,
    "enable_memory_saver": false,
    "enable_weights_cpu_backup": false,
    "enable_draft_weights_cpu_backup": false,
    "allow_auto_truncate": false,
    "enable_custom_logit_processor": false,
    "flashinfer_mla_disable_ragged": false,
    "disable_shared_experts_fusion": false,
    "disable_chunked_prefix_cache": false,
    "disable_fast_image_processor": false,
    "keep_mm_feature_on_device": false,
    "enable_return_hidden_states": false,
    "enable_return_routed_experts": false,
    "scheduler_recv_interval": 1,
    "numa_node": null,
    "enable_deterministic_inference": false,
    "rl_on_policy_target": null,
    "enable_attn_tp_input_scattered": false,
    "enable_nsa_prefill_context_parallel": false,
    "nsa_prefill_cp_mode": "round-robin-split",
    "enable_fused_qk_norm_rope": false,
    "enable_precise_embedding_interpolation": false,
    "enable_dynamic_batch_tokenizer": false,
    "dynamic_batch_tokenizer_batch_size": 32,
    "dynamic_batch_tokenizer_batch_timeout": 0.002,
    "debug_tensor_dump_output_folder": null,
    "debug_tensor_dump_layers": null,
    "debug_tensor_dump_input_file": null,
    "debug_tensor_dump_inject": false,
    "disaggregation_mode": "prefill",
    "disaggregation_transfer_backend": "nixl",
    "disaggregation_bootstrap_port": 8998,
    "disaggregation_decode_tp": 16,
    "disaggregation_decode_dp": 1,
    "disaggregation_prefill_pp": 1,
    "disaggregation_ib_device": "mlx5_0,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_9,mlx5_10,mlx5_11",
    "disaggregation_decode_enable_offload_kvcache": false,
    "num_reserved_decode_tokens": 512,
    "disaggregation_decode_polling_interval": 1,
    "encoder_only": false,
    "language_only": false,
    "encoder_transfer_backend": "zmq_to_scheduler",
    "encoder_urls": [],
    "custom_weight_loader": [],
    "weight_loader_disable_mmap": false,
    "remote_instance_weight_loader_seed_instance_ip": null,
    "remote_instance_weight_loader_seed_instance_service_port": null,
    "remote_instance_weight_loader_send_weights_group_ports": null,
    "remote_instance_weight_loader_backend": "nccl",
    "remote_instance_weight_loader_start_seed_via_transfer_engine": false,
    "enable_pdmux": false,
    "pdmux_config_path": null,
    "sm_group_num": 8,
    "mm_max_concurrent_calls": 32,
    "mm_per_request_timeout": 10.0,
    "enable_broadcast_mm_inputs_process": false,
    "enable_prefix_mm_cache": false,
    "mm_enable_dp_encoder": false,
    "mm_process_config": {},
    "limit_mm_data_per_request": null,
    "decrypted_config_file": null,
    "decrypted_draft_config_file": null,
    "forward_hooks": null,
    "status": "ready",
    "max_total_num_tokens": 326223,
    "max_req_input_len": 163834,
    "internal_states": [
        {
            "model_path": "/app/models/Deepseek-R1/",
            "tokenizer_path": "/app/models/Deepseek-R1/",
            "tokenizer_mode": "auto",
            "tokenizer_worker_num": 1,
            "skip_tokenizer_init": false,
            "load_format": "auto",
            "model_loader_extra_config": "{}",
            "trust_remote_code": true,
            "context_length": null,
            "is_embedding": false,
            "enable_multimodal": null,
            "revision": null,
            "model_impl": "auto",
            "host": "10.99.91.39",
            "port": 30000,
            "fastapi_root_path": "",
            "grpc_mode": false,
            "skip_server_warmup": false,
            "warmups": null,
            "nccl_port": null,
            "checkpoint_engine_wait_weights_before_ready": false,
            "dtype": "auto",
            "quantization": null,
            "quantization_param_path": null,
            "kv_cache_dtype": "auto",
            "enable_fp32_lm_head": false,
            "modelopt_quant": null,
            "modelopt_checkpoint_restore_path": null,
            "modelopt_checkpoint_save_path": null,
            "modelopt_export_path": null,
            "quantize_and_serve": false,
            "rl_quant_profile": null,
            "mem_fraction_static": 0.8,
            "max_running_requests": null,
            "max_queued_requests": null,
            "max_total_tokens": null,
            "chunked_prefill_size": 8192,
            "enable_dynamic_chunking": false,
            "max_prefill_tokens": 16384,
            "prefill_max_requests": null,
            "schedule_policy": "fcfs",
            "enable_priority_scheduling": false,
            "abort_on_priority_when_disabled": false,
            "schedule_low_priority_values_first": false,
            "priority_scheduling_preemption_threshold": 10,
            "schedule_conservativeness": 1.0,
            "page_size": 1,
            "swa_full_tokens_ratio": 0.8,
            "disable_hybrid_swa_memory": false,
            "radix_eviction_policy": "lru",
            "enable_prefill_delayer": false,
            "prefill_delayer_max_delay_passes": 30,
            "prefill_delayer_token_usage_low_watermark": null,
            "prefill_delayer_forward_passes_buckets": null,
            "prefill_delayer_wait_seconds_buckets": null,
            "device": "cuda",
            "tp_size": 16,
            "pp_size": 1,
            "pp_max_micro_batch_size": 2048,
            "pp_async_batch_depth": 0,
            "stream_interval": 1,
            "stream_output": false,
            "random_seed": 128558095,
            "constrained_json_whitespace_pattern": null,
            "constrained_json_disable_any_whitespace": false,
            "watchdog_timeout": 300,
            "soft_watchdog_timeout": null,
            "dist_timeout": null,
            "download_dir": null,
            "model_checksum": null,
            "base_gpu_id": 0,
            "gpu_id_step": 1,
            "sleep_on_idle": false,
            "custom_sigquit_handler": null,
            "log_level": "info",
            "log_level_http": null,
            "log_requests": false,
            "log_requests_level": 2,
            "log_requests_format": "text",
            "log_requests_target": null,
            "uvicorn_access_log_exclude_prefixes": [],
            "crash_dump_folder": null,
            "show_time_cost": false,
            "enable_metrics": false,
            "enable_metrics_for_all_schedulers": false,
            "tokenizer_metrics_custom_labels_header": "x-custom-labels",
            "tokenizer_metrics_allowed_custom_labels": null,
            "extra_metric_labels": null,
            "bucket_time_to_first_token": null,
            "bucket_inter_token_latency": null,
            "bucket_e2e_request_latency": null,
            "collect_tokens_histogram": false,
            "prompt_tokens_buckets": null,
            "generation_tokens_buckets": null,
            "gc_warning_threshold_secs": 0.0,
            "decode_log_interval": 40,
            "enable_request_time_stats_logging": false,
            "kv_events_config": null,
            "enable_trace": false,
            "otlp_traces_endpoint": "localhost:4317",
            "export_metrics_to_file": false,
            "export_metrics_to_file_dir": null,
            "api_key": null,
            "admin_api_key": null,
            "served_model_name": "/app/models/Deepseek-R1/",
            "weight_version": "default",
            "chat_template": null,
            "hf_chat_template_name": null,
            "completion_template": null,
            "file_storage_path": "sglang_storage",
            "enable_cache_report": false,
            "reasoning_parser": null,
            "tool_call_parser": null,
            "tool_server": null,
            "sampling_defaults": "model",
            "dp_size": 1,
            "load_balance_method": "follow_bootstrap_room",
            "attn_cp_size": 1,
            "moe_dp_size": 1,
            "dist_init_addr": "10.99.91.39:5000",
            "nnodes": 2,
            "node_rank": 0,
            "json_model_override_args": "{}",
            "preferred_sampling_params": null,
            "enable_lora": null,
            "enable_lora_overlap_loading": null,
            "max_lora_rank": null,
            "lora_target_modules": null,
            "lora_paths": null,
            "max_loaded_loras": null,
            "max_loras_per_batch": 8,
            "lora_eviction_policy": "lru",
            "lora_backend": "csgmv",
            "max_lora_chunk_size": 16,
            "attention_backend": "fa3",
            "decode_attention_backend": "fa3",
            "prefill_attention_backend": "fa3",
            "sampling_backend": "flashinfer",
            "grammar_backend": "xgrammar",
            "mm_attention_backend": null,
            "fp8_gemm_runner_backend": "auto",
            "fp4_gemm_runner_backend": "flashinfer_cutlass",
            "nsa_prefill_backend": null,
            "nsa_decode_backend": null,
            "disable_flashinfer_autotune": false,
            "mamba_backend": "triton",
            "speculative_algorithm": null,
            "speculative_draft_model_path": null,
            "speculative_draft_model_revision": null,
            "speculative_draft_load_format": null,
            "speculative_num_steps": null,
            "speculative_eagle_topk": null,
            "speculative_num_draft_tokens": null,
            "speculative_accept_threshold_single": 1.0,
            "speculative_accept_threshold_acc": 1.0,
            "speculative_token_map": null,
            "speculative_attention_mode": "prefill",
            "speculative_draft_attention_backend": null,
            "speculative_moe_runner_backend": "auto",
            "speculative_moe_a2a_backend": null,
            "speculative_draft_model_quantization": null,
            "speculative_ngram_min_match_window_size": 1,
            "speculative_ngram_max_match_window_size": 12,
            "speculative_ngram_min_bfs_breadth": 1,
            "speculative_ngram_max_bfs_breadth": 10,
            "speculative_ngram_match_type": "BFS",
            "speculative_ngram_branch_length": 18,
            "speculative_ngram_capacity": 10000000,
            "enable_multi_layer_eagle": false,
            "ep_size": 1,
            "moe_a2a_backend": "none",
            "moe_runner_backend": "auto",
            "flashinfer_mxfp4_moe_precision": "default",
            "enable_flashinfer_allreduce_fusion": false,
            "deepep_mode": "auto",
            "ep_num_redundant_experts": 0,
            "ep_dispatch_algorithm": null,
            "init_expert_location": "trivial",
            "enable_eplb": false,
            "eplb_algorithm": "auto",
            "eplb_rebalance_num_iterations": 1000,
            "eplb_rebalance_layers_per_chunk": null,
            "eplb_min_rebalancing_utilization_threshold": 1.0,
            "expert_distribution_recorder_mode": null,
            "expert_distribution_recorder_buffer_size": 1000,
            "enable_expert_distribution_metrics": false,
            "deepep_config": null,
            "moe_dense_tp_size": null,
            "elastic_ep_backend": null,
            "mooncake_ib_device": null,
            "max_mamba_cache_size": null,
            "mamba_ssm_dtype": null,
            "mamba_full_memory_ratio": 0.9,
            "mamba_scheduler_strategy": "no_buffer",
            "mamba_track_interval": 256,
            "enable_hierarchical_cache": false,
            "hicache_ratio": 2.0,
            "hicache_size": 0,
            "hicache_write_policy": "write_through",
            "hicache_io_backend": "kernel",
            "hicache_mem_layout": "layer_first",
            "disable_hicache_numa_detect": false,
            "hicache_storage_backend": null,
            "hicache_storage_prefetch_policy": "best_effort",
            "hicache_storage_backend_extra_config": null,
            "hierarchical_sparse_attention_extra_config": null,
            "enable_lmcache": false,
            "kt_weight_path": null,
            "kt_method": "AMXINT4",
            "kt_cpuinfer": null,
            "kt_threadpool_count": 2,
            "kt_num_gpu_experts": null,
            "kt_max_deferred_experts_per_token": null,
            "dllm_algorithm": null,
            "dllm_algorithm_config": null,
            "enable_double_sparsity": false,
            "ds_channel_config_path": null,
            "ds_heavy_channel_num": 32,
            "ds_heavy_token_num": 256,
            "ds_heavy_channel_type": "qk",
            "ds_sparse_decode_threshold": 4096,
            "cpu_offload_gb": 0,
            "offload_group_size": -1,
            "offload_num_in_group": 1,
            "offload_prefetch_step": 1,
            "offload_mode": "cpu",
            "multi_item_scoring_delimiter": null,
            "disable_radix_cache": false,
            "cuda_graph_max_bs": 512,
            "cuda_graph_bs": [
                1,
                2,
                4,
                8,
                12,
                16,
                24,
                32,
                40,
                48,
                56,
                64,
                72,
                80,
                88,
                96,
                104,
                112,
                120,
                128,
                136,
                144,
                152,
                160,
                168,
                176,
                184,
                192,
                200,
                208,
                216,
                224,
                232,
                240,
                248,
                256,
                272,
                288,
                304,
                320,
                336,
                352,
                368,
                384,
                400,
                416,
                432,
                448,
                464,
                480,
                496,
                512
            ],
            "disable_cuda_graph": true,
            "disable_cuda_graph_padding": false,
            "enable_profile_cuda_graph": false,
            "enable_cudagraph_gc": false,
            "enable_layerwise_nvtx_marker": false,
            "enable_nccl_nvls": false,
            "enable_symm_mem": false,
            "disable_flashinfer_cutlass_moe_fp4_allgather": false,
            "enable_tokenizer_batch_encode": false,
            "disable_tokenizer_batch_decode": false,
            "disable_outlines_disk_cache": false,
            "disable_custom_all_reduce": false,
            "enable_mscclpp": false,
            "enable_torch_symm_mem": false,
            "disable_overlap_schedule": false,
            "enable_mixed_chunk": false,
            "enable_dp_attention": false,
            "enable_dp_lm_head": false,
            "enable_two_batch_overlap": false,
            "enable_single_batch_overlap": false,
            "tbo_token_distribution_threshold": 0.48,
            "enable_torch_compile": false,
            "enable_piecewise_cuda_graph": false,
            "enable_torch_compile_debug_mode": false,
            "torch_compile_max_bs": 32,
            "piecewise_cuda_graph_max_tokens": 2048,
            "piecewise_cuda_graph_tokens": [
                4,
                8,
                12,
                16,
                20,
                24,
                28,
                32,
                48,
                64,
                80,
                96,
                112,
                128,
                144,
                160,
                176,
                192,
                208,
                224,
                240,
                256,
                288,
                320,
                352,
                384,
                416,
                448,
                480,
                512,
                576,
                640,
                704,
                768,
                832,
                896,
                960,
                1024,
                1280,
                1536,
                1792,
                2048
            ],
            "piecewise_cuda_graph_compiler": "eager",
            "torchao_config": "",
            "enable_nan_detection": false,
            "enable_p2p_check": false,
            "triton_attention_reduce_in_fp32": false,
            "triton_attention_num_kv_splits": 8,
            "triton_attention_split_tile_size": null,
            "num_continuous_decode_steps": 1,
            "delete_ckpt_after_loading": false,
            "enable_memory_saver": false,
            "enable_weights_cpu_backup": false,
            "enable_draft_weights_cpu_backup": false,
            "allow_auto_truncate": false,
            "enable_custom_logit_processor": false,
            "flashinfer_mla_disable_ragged": false,
            "disable_shared_experts_fusion": false,
            "disable_chunked_prefix_cache": false,
            "disable_fast_image_processor": false,
            "keep_mm_feature_on_device": false,
            "enable_return_hidden_states": false,
            "enable_return_routed_experts": false,
            "scheduler_recv_interval": 1,
            "numa_node": null,
            "enable_deterministic_inference": false,
            "rl_on_policy_target": null,
            "enable_attn_tp_input_scattered": false,
            "enable_nsa_prefill_context_parallel": false,
            "nsa_prefill_cp_mode": "round-robin-split",
            "enable_fused_qk_norm_rope": false,
            "enable_precise_embedding_interpolation": false,
            "enable_dynamic_batch_tokenizer": false,
            "dynamic_batch_tokenizer_batch_size": 32,
            "dynamic_batch_tokenizer_batch_timeout": 0.002,
            "debug_tensor_dump_output_folder": null,
            "debug_tensor_dump_layers": null,
            "debug_tensor_dump_input_file": null,
            "debug_tensor_dump_inject": false,
            "disaggregation_mode": "prefill",
            "disaggregation_transfer_backend": "nixl",
            "disaggregation_bootstrap_port": 8998,
            "disaggregation_decode_tp": 16,
            "disaggregation_decode_dp": 1,
            "disaggregation_prefill_pp": 1,
            "disaggregation_ib_device": "mlx5_0,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_9,mlx5_10,mlx5_11",
            "disaggregation_decode_enable_offload_kvcache": false,
            "num_reserved_decode_tokens": 512,
            "disaggregation_decode_polling_interval": 1,
            "encoder_only": false,
            "language_only": false,
            "encoder_transfer_backend": "zmq_to_scheduler",
            "encoder_urls": [],
            "custom_weight_loader": [],
            "weight_loader_disable_mmap": false,
            "remote_instance_weight_loader_seed_instance_ip": null,
            "remote_instance_weight_loader_seed_instance_service_port": null,
            "remote_instance_weight_loader_send_weights_group_ports": null,
            "remote_instance_weight_loader_backend": "nccl",
            "remote_instance_weight_loader_start_seed_via_transfer_engine": false,
            "enable_pdmux": false,
            "pdmux_config_path": null,
            "sm_group_num": 8,
            "mm_max_concurrent_calls": 32,
            "mm_per_request_timeout": 10.0,
            "enable_broadcast_mm_inputs_process": false,
            "enable_prefix_mm_cache": false,
            "mm_enable_dp_encoder": false,
            "mm_process_config": {},
            "limit_mm_data_per_request": null,
            "decrypted_config_file": null,
            "decrypted_draft_config_file": null,
            "forward_hooks": null,
            "use_mla_backend": true,
            "last_gen_throughput": 0.0,
            "memory_usage": {
                "weight": 40.62,
                "kvcache": 21.35,
                "token_capacity": 326223,
                "graph": 0
            },
            "effective_max_running_requests_per_dp": 2048
        }
    ],
    "version": "0.5.9"
}




[dcbsr_dev@tpgds-aihub0003 ~]$ python3 -m sglang.bench_serving \
  --backend sglang \
  --host 10.99.91.39 \
  --port 8000 \
  --num-prompts 20 \
  --request-rate 4 \
  --input-len 512 \
  --output-len 128
/usr/bin/python3: Error while finding module specification for 'sglang.bench_serving' (ModuleNotFoundError: No module named 'sglang')
[dcbsr_dev@tpgds-aihub0003 ~]$ . /app/sglang/sglang-latest/bin/activate
((sglang-0.5.9) ) [dcbsr_dev@tpgds-aihub0003 ~]$ python3 -m sglang.bench_serving   --backend sglang   --host 10.99.91.39   --port 8000   --num-prompts 20   --request-rate 4   --input-len 512   --output-len 128
usage: bench_serving.py [-h] [--backend {sglang,sglang-native,sglang-oai,sglang-oai-chat,vllm,vllm-chat,lmdeploy,lmdeploy-chat,trt,gserver,truss}]
                        [--base-url BASE_URL] [--host HOST] [--port PORT]
                        [--dataset-name {sharegpt,custom,openai,random,random-ids,generated-shared-prefix,mmmu,image,mooncake}]
                        [--dataset-path DATASET_PATH] [--model MODEL] [--served-model-name SERVED_MODEL_NAME] [--tokenizer TOKENIZER]
                        [--num-prompts NUM_PROMPTS] [--sharegpt-output-len SHAREGPT_OUTPUT_LEN] [--sharegpt-context-len SHAREGPT_CONTEXT_LEN]
                        [--random-input-len RANDOM_INPUT_LEN] [--random-output-len RANDOM_OUTPUT_LEN] [--random-range-ratio RANDOM_RANGE_RATIO]
                        [--image-count IMAGE_COUNT] [--image-resolution IMAGE_RESOLUTION] [--random-image-count] [--image-format IMAGE_FORMAT]
                        [--image-content IMAGE_CONTENT] [--request-rate REQUEST_RATE] [--use-trace-timestamps] [--max-concurrency MAX_CONCURRENCY]
                        [--output-file OUTPUT_FILE] [--output-details] [--print-requests] [--disable-tqdm] [--disable-stream] [--return-logprob]
                        [--return-routed-experts] [--seed SEED] [--disable-ignore-eos] [--extra-request-body {"key1": "value1", "key2": "value2"}]
                        [--apply-chat-template] [--profile] [--plot-throughput]
                        [--profile-activities {CPU,GPU,CUDA_PROFILER} [{CPU,GPU,CUDA_PROFILER} ...]] [--profile-num-steps PROFILE_NUM_STEPS]
                        [--profile-by-stage] [--profile-stages PROFILE_STAGES [PROFILE_STAGES ...]] [--profile-output-dir PROFILE_OUTPUT_DIR]
                        [--profile-prefix PROFILE_PREFIX] [--lora-name [LORA_NAME ...]] [--lora-request-distribution {uniform,distinct,skewed}]
                        [--lora-zipf-alpha LORA_ZIPF_ALPHA] [--prompt-suffix PROMPT_SUFFIX] [--pd-separated]
                        [--profile-prefill-url [PROFILE_PREFILL_URL ...] | --profile-decode-url [PROFILE_DECODE_URL ...]] [--flush-cache]
                        [--warmup-requests WARMUP_REQUESTS] [--tokenize-prompt] [--gsp-num-groups GSP_NUM_GROUPS]
                        [--gsp-prompts-per-group GSP_PROMPTS_PER_GROUP] [--gsp-system-prompt-len GSP_SYSTEM_PROMPT_LEN]
                        [--gsp-question-len GSP_QUESTION_LEN] [--gsp-output-len GSP_OUTPUT_LEN] [--gsp-range-ratio GSP_RANGE_RATIO]
                        [--gsp-fast-prepare] [--gsp-send-routing-key] [--gsp-num-turns GSP_NUM_TURNS] [--gsp-ordered]
                        [--mooncake-slowdown-factor MOONCAKE_SLOWDOWN_FACTOR] [--mooncake-num-rounds MOONCAKE_NUM_ROUNDS]
                        [--mooncake-workload {mooncake,conversation,synthetic,toolagent}] [--tag TAG] [--header HEADER [HEADER ...]]
bench_serving.py: error: unrecognized arguments: --input-len 512 --output-len 128



