# roles/pyxis/handlers/main.yml
---
# =============================================================================
# PYXIS HANDLERS
# =============================================================================

- name: restart slurmctld
  systemd:
    name: slurmctld
    state: restarted
    daemon_reload: yes
  listen: "restart slurmctld"
  when: is_controller | bool

- name: restart slurmd
  systemd:
    name: slurmd
    state: restarted
    daemon_reload: yes
  listen: "restart slurmd"
  when: is_compute | bool