---
# Обработчики событий для роли common

- name: restart munge
  systemd:
    name: munge
    state: restarted
    daemon_reload: yes

- name: restart nfs-server
  systemd:
    name: nfs-kernel-server
    state: restarted
    daemon_reload: yes

- name: reload nfs-exports
  command: exportfs -ra

- name: restart nfs-common
  systemd:
    name: nfs-common
    state: restarted
    daemon_reload: yes

- name: remount nfs
  mount:
    path: "{{ item }}"
    state: remounted
  loop:
    - /shared
    - /home/shared