# roles/containers/tasks/main.yml
---
# =============================================================================
# УСТАНОВКА ENROOT + PYXIS (ОФИЦИАЛЬНЫЙ ПОДХОД)
# =============================================================================

- name: "[CONTAINERS] Начало установки контейнеров"
  debug:
    msg: |
      🐳 Установка Enroot + Pyxis на {{ inventory_hostname }}
      📍 Роль: {{ group_names | join(', ') }}
      🎯 Официальный подход: make install + готовый конфиг

# =============================================================================
# ПРОВЕРКА ПРЕДВАРИТЕЛЬНЫХ ТРЕБОВАНИЙ
# =============================================================================

- name: "[CONTAINERS] Проверка Slurm headers"
  stat:
    path: "{{ slurm_install_prefix }}/include/slurm/spank.h"
  register: headers_check
  failed_when: not headers_check.stat.exists

# - name: "[CONTAINERS] Подтверждение headers"
#   debug:
#     msg: |
#       ✅ Headers найдены: {{ slurm_install_prefix }}/include/slurm/spank.h
#       📊 Количество: {{ ansible_facts | json_query('[?path==`' + slurm_install_prefix + '/include`] | length(@)') | default('много') }}

# =============================================================================
# УСТАНОВКА СИСТЕМНЫХ ЗАВИСИМОСТЕЙ
# =============================================================================

- name: "[CONTAINERS] Установка зависимостей"
  apt:
    name: "{{ enroot_system_packages + pyxis_build_packages }}"
    state: present
    update_cache: yes

- name: "[CONTAINERS] Создание директорий"
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ enroot_config_dir }}"
    - "{{ enroot_data_dir }}"
    - "{{ enroot_cache_dir }}"
    - "{{ enroot_runtime_path }}"
    - "{{ plugstack_config_dir }}"
    - /tmp/containers-build

# =============================================================================
# УСТАНОВКА ENROOT
# =============================================================================

- name: "[ENROOT] Проверка установки"
  command: enroot version
  register: enroot_check
  failed_when: false
  changed_when: false

- name: "[ENROOT] Установка Enroot"
  block:
    - name: "Скачивание Enroot DEB"
      get_url:
        url: "{{ enroot_download_url }}/enroot_{{ enroot_version }}-1_amd64.deb"
        dest: "/tmp/containers-build/enroot_{{ enroot_version }}-1_amd64.deb"
        timeout: 300
        
    - name: "Установка Enroot из DEB"
      apt:
        deb: "/tmp/containers-build/enroot_{{ enroot_version }}-1_amd64.deb"
        state: present
  when: enroot_check.rc != 0

- name: "[ENROOT] Конфигурация Enroot"
  template:
    src: enroot.conf.j2
    dest: "{{ enroot_config_dir }}/enroot.conf"
    mode: '0644'

# =============================================================================
# УСТАНОВКА PYXIS (ОФИЦИАЛЬНЫЙ СПОСОБ!)
# =============================================================================

- name: "[PYXIS] Очистка старых файлов"
  file:
    path: "{{ pyxis_build_dir }}"
    state: absent
  when: inventory_hostname in groups['slurm_compute'] or inventory_hostname in groups['slurm_login']

- name: "[PYXIS] Создание build директории"
  file:
    path: "{{ pyxis_build_dir }}"
    state: directory
    mode: '0755'
  when: inventory_hostname in groups['slurm_compute'] or inventory_hostname in groups['slurm_login']

- name: "[PYXIS] Скачивание исходников"
  get_url:
    url: "{{ pyxis_download_url }}"
    dest: "/tmp/containers-build/pyxis-{{ pyxis_version }}.tar.gz"
    timeout: 300
  when: inventory_hostname in groups['slurm_compute'] or inventory_hostname in groups['slurm_login']

- name: "[PYXIS] Извлечение исходников"
  unarchive:
    src: "/tmp/containers-build/pyxis-{{ pyxis_version }}.tar.gz"
    dest: "{{ pyxis_build_dir }}"
    remote_src: yes
    extra_opts: ["--strip-components=1"]
  when: inventory_hostname in groups['slurm_compute'] or inventory_hostname in groups['slurm_login']

- name: "[PYXIS] ОФИЦИАЛЬНАЯ компиляция и установка"
  shell: |
    cd {{ pyxis_build_dir }}
    
    echo "=== ОФИЦИАЛЬНАЯ УСТАНОВКА PYXIS ==="
    echo "Используем headers: {{ slurm_install_prefix }}/include"
    
    # Компиляция с правильными headers
    export CPPFLAGS="-I{{ slurm_install_prefix }}/include"
    export LDFLAGS="-L{{ slurm_install_prefix }}/lib"
    
    # Очистка и сборка
    make clean || true
    make
    
    # ОФИЦИАЛЬНАЯ УСТАНОВКА (ключевой момент!)
    sudo make install
    
    echo "✅ Pyxis установлен официально!"
    echo "Плагин: $(find /usr/local -name 'spank_pyxis.so' -type f)"
    echo "Конфиг: $(find /usr/local -name 'pyxis.conf' -type f)"
    
  register: pyxis_install
  when: inventory_hostname in groups['slurm_compute'] or inventory_hostname in groups['slurm_login'] or ['slurm_master']

- name: "[PYXIS] Результат установки"
  debug:
    var: pyxis_install.stdout_lines
  when: inventory_hostname in groups['slurm_compute'] or inventory_hostname in groups['slurm_login']

# =============================================================================
# ОФИЦИАЛЬНАЯ КОНФИГУРАЦИЯ (как в документации!)
# =============================================================================

- name: "[CONFIG] Создание plugstack.conf.d директории"
  file:
    path: "{{ plugstack_config_dir }}"
    state: directory
    mode: '0755'
  when: inventory_hostname in groups['slurm_compute'] or inventory_hostname in groups['slurm_login']

- name: "[CONFIG] ОФИЦИАЛЬНАЯ символическая ссылка на конфиг"
  file:
    src: /usr/local/share/pyxis/pyxis.conf
    dest: "{{ plugstack_config_dir }}/pyxis.conf"
    state: link
    force: yes
  when: inventory_hostname in groups['slurm_compute'] or inventory_hostname in groups['slurm_login']

# =============================================================================
# ПЕРЕЗАПУСК СЕРВИСОВ
# =============================================================================

- name: "[RESTART] Перезапуск slurmd на compute узлах"
  systemd:
    name: slurmd
    state: restarted
    daemon_reload: yes
  when: inventory_hostname in groups['slurm_compute']

- name: "[RESTART] Пауза после перезапуска"
  pause:
    seconds: 3

# =============================================================================
# ПРОВЕРКА УСТАНОВКИ
# =============================================================================

- name: "[VERIFY] Проверка Enroot"
  command: enroot version
  register: enroot_verify
  changed_when: false

- name: "[VERIFY] Проверка установленного Pyxis"
  shell: |
    echo "=== ПРОВЕРКА PYXIS ==="
    
    # Проверяем установленный плагин
    if [ -f /usr/local/lib/slurm/spank_pyxis.so ]; then
      echo "✅ Плагин: $(ls -la /usr/local/lib/slurm/spank_pyxis.so)"
    else
      echo "❌ Плагин не найден"
    fi
    
    # Проверяем конфиг
    if [ -f /usr/local/share/pyxis/pyxis.conf ]; then
      echo "✅ Конфиг: $(ls -la /usr/local/share/pyxis/pyxis.conf)"
    else
      echo "❌ Конфиг не найден"  
    fi
    
    # Проверяем ссылку
    if [ -L {{ plugstack_config_dir }}/pyxis.conf ]; then
      echo "✅ Ссылка: $(ls -la {{ plugstack_config_dir }}/pyxis.conf)"
    else
      echo "❌ Ссылка не создана"
    fi
    
  register: pyxis_verify
  when: inventory_hostname in groups['slurm_compute'] or inventory_hostname in groups['slurm_login']
  changed_when: false

- name: "[VERIFY] Проверка slurmd (только compute)"
  shell: systemctl is-active slurmd
  register: slurmd_verify
  when: inventory_hostname in groups['slurm_compute']
  failed_when: false
  changed_when: false

# =============================================================================
# ФИНАЛЬНАЯ ИНФОРМАЦИЯ
# =============================================================================

- name: "[CONTAINERS] Результат установки"
  debug:
    msg: |
      ✅ Контейнерная поддержка установлена на {{ inventory_hostname }}!
      
      📦 Enroot: {{ enroot_verify.stdout }}
      
      {% if inventory_hostname in groups['slurm_compute'] or inventory_hostname in groups['slurm_login'] %}
      🔌 Pyxis (официальная установка):
      {{ pyxis_verify.stdout }}
      
      {% if inventory_hostname in groups['slurm_compute'] %}
      🔧 slurmd: {{ slurmd_verify.stdout | default('неизвестно') }}
      {% endif %}
      {% endif %}
      
      🎯 Установка выполнена по официальной документации:
      - make install (системная установка)  
      - готовый конфиг через символическую ссылку
      - поддержка на compute И login узлах
      
      🚀 Готов к запуску контейнеров!