# roles/containers/tasks/main.yml
---
# МИНИМАЛЬНОЕ ИСПРАВЛЕНИЕ - ТОЛЬКО ПРОБЛЕМА С PYXIS

- name: "[CONTAINERS] Исправление Pyxis (минимальные изменения)"
  debug:
    msg: "Исправляем только проблему с Pyxis, сохраняя вашу архитектуру"

- name: "[CONTAINERS] Задание переменных"
  set_fact:
    pyxis_build_dir: "/tmp/pyxis-build"
    pyxis_version: "0.20.0"
    pyxis_download_url: "https://github.com/NVIDIA/pyxis/archive/v0.20.0.tar.gz"

# =============================================================================
# СИСТЕМНЫЕ ЗАВИСИМОСТИ (ДОБАВЛЯЕМ ТОЛЬКО НУЖНОЕ)
# =============================================================================

- name: "[CONTAINERS] Установка libslurm-dev (для headers)"
  apt:
    name: libslurm-dev
    state: present
    update_cache: yes

# =============================================================================
# ВАША ОРИГИНАЛЬНАЯ УСТАНОВКА ENROOT (БЕЗ ИЗМЕНЕНИЙ)
# =============================================================================

- name: "[CONTAINERS] Проверка установки Enroot"
  command: enroot version
  register: enroot_check
  failed_when: false
  changed_when: false

- name: "[CONTAINERS] Установка Enroot"
  shell: |
    if ! command -v enroot >/dev/null 2>&1; then
      cd /tmp
      wget -q https://github.com/NVIDIA/enroot/releases/download/v3.5.0/enroot_3.5.0-1_amd64.deb
      apt install -y ./enroot_3.5.0-1_amd64.deb
      echo "Enroot установлен"
    else
      echo "Enroot уже установлен"
    fi
  register: enroot_install

# =============================================================================
# ИСПРАВЛЕННАЯ УСТАНОВКА PYXIS (ГЛАВНОЕ ИСПРАВЛЕНИЕ!)
# =============================================================================

- name: "[PYXIS] Очистка старых файлов"
  file:
    path: "{{ pyxis_build_dir }}"
    state: absent

- name: "[PYXIS] Создание build директории"
  file:
    path: "{{ pyxis_build_dir }}"
    state: directory
    mode: '0755'

- name: "[PYXIS] Скачивание исходников"
  get_url:
    url: "{{ pyxis_download_url }}"
    dest: "/tmp/pyxis-{{ pyxis_version }}.tar.gz"
    timeout: 300

- name: "[PYXIS] Извлечение исходников"
  unarchive:
    src: "/tmp/pyxis-{{ pyxis_version }}.tar.gz"
    dest: "{{ pyxis_build_dir }}"
    remote_src: yes
    extra_opts: ["--strip-components=1"]

- name: "[PYXIS] ИСПРАВЛЕННАЯ компиляция"
  shell: |
    cd {{ pyxis_build_dir }}
    
    echo "=== ИСПРАВЛЕННАЯ КОМПИЛЯЦИЯ PYXIS ==="
    
    # ПРОБУЕМ НЕСКОЛЬКО ПУТЕЙ К HEADERS
    if [ -f /opt/slurm/include/slurm/spank.h ]; then
      HEADER_PATH="/opt/slurm/include"
      echo "Используем ваши скомпилированные headers: $HEADER_PATH"
    elif [ -f /usr/include/slurm/spank.h ]; then
      HEADER_PATH="/usr/include"
      echo "Используем системные headers: $HEADER_PATH"
    else
      echo "❌ Headers не найдены!"
      exit 1
    fi
    
    # ПРОБУЕМ НЕСКОЛЬКО ПУТЕЙ К БИБЛИОТЕКАМ
    if [ -f /opt/slurm/lib/libslurm.so ]; then
      LIB_PATH="/opt/slurm/lib"
      echo "Используем ваши скомпилированные библиотеки: $LIB_PATH"
    elif [ -f /usr/lib/x86_64-linux-gnu/libslurm.so ]; then
      LIB_PATH="/usr/lib/x86_64-linux-gnu"
      echo "Используем системные библиотеки: $LIB_PATH"
    else
      echo "❌ Библиотеки не найдены!"
      exit 1
    fi
    
    # Компиляция с найденными путями
    export CPPFLAGS="-I${HEADER_PATH}"
    export LDFLAGS="-L${LIB_PATH}"
    
    make clean || true
    make
    
    # Установка
    make install
    
    echo "✅ Pyxis установлен!"
    ls -la /usr/local/lib/slurm/spank_pyxis.so
    
  register: pyxis_install

# =============================================================================
# ВАША ОРИГИНАЛЬНАЯ КОНФИГУРАЦИЯ (ИСПРАВЛЯЕМ ТОЛЬКО ПУТЬ)
# =============================================================================

- name: "[CONFIG] Создание ПРАВИЛЬНОГО plugstack.conf"
  copy:
    dest: /etc/slurm/plugstack.conf
    content: |
      # Slurm SPANK Plugin Stack Configuration
      required /usr/local/lib/slurm/spank_pyxis.so
    owner: root
    group: root
    mode: '0644'

# =============================================================================
# ВАШИ ОРИГИНАЛЬНЫЕ ДИРЕКТОРИИ ENROOT (БЕЗ ИЗМЕНЕНИЙ)
# =============================================================================

- name: "[ENROOT] Создание директорий Enroot"
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /var/lib/enroot
    - /var/cache/enroot
    - /run/enroot
    - /etc/enroot

- name: "[ENROOT] Конфигурация Enroot"
  copy:
    dest: /etc/enroot/enroot.conf
    content: |
      ENROOT_DATA_PATH /var/lib/enroot
      ENROOT_CACHE_PATH /var/cache/enroot
      ENROOT_RUNTIME_PATH /run/enroot
      ENROOT_MOUNT_HOME /home:/home
      ENROOT_MOUNT_HOME /sw:/sw
      ENROOT_ALLOW_PRIVILEGED yes
    mode: '0644'

# =============================================================================
# МИНИМАЛЬНАЯ ПРОВЕРКА
# =============================================================================

- name: "[VERIFY] Проверка исправления"
  shell: |
    echo "=== ПРОВЕРКА ИСПРАВЛЕНИЙ ==="
    
    if [ -f /usr/local/lib/slurm/spank_pyxis.so ]; then
      echo "✅ Pyxis plugin: $(ls -la /usr/local/lib/slurm/spank_pyxis.so)"
    else
      echo "❌ Pyxis plugin НЕ НАЙДЕН"
    fi
    
    if [ -f /etc/slurm/plugstack.conf ]; then
      echo "✅ plugstack.conf:"
      cat /etc/slurm/plugstack.conf
    else
      echo "❌ plugstack.conf НЕ НАЙДЕН"
    fi
    
  register: fix_verify
  changed_when: false

- name: "[CONTAINERS] Результат исправления"
  debug:
    msg: |
      🔧 Минимальное исправление завершено:
      {{ fix_verify.stdout }}
      
      Теперь перезапустите slurmd:
      sudo systemctl restart slurmd