# roles/containers/defaults/main.yml
---
# =============================================================================
# ПЕРЕМЕННЫЕ ДЛЯ ENROOT + PYXIS (ОФИЦИАЛЬНЫЙ ПОДХОД)
# =============================================================================

# Версии компонентов
enroot_version: "3.5.0"
pyxis_version: "0.20.0"

# URL для скачивания
enroot_download_url: "https://github.com/NVIDIA/enroot/releases/download/v{{ enroot_version }}"
pyxis_download_url: "https://github.com/NVIDIA/pyxis/archive/v{{ pyxis_version }}.tar.gz"

# =============================================================================
# СИСТЕМНЫЕ ПУТИ (ЕДИНООБРАЗИЕ)
# =============================================================================

# Slurm installation prefix (должен совпадать с slurm_build!)
slurm_install_prefix: "/opt/slurm"

# Enroot пути
enroot_config_dir: "/etc/enroot"
enroot_data_dir: "/var/lib/enroot"
enroot_cache_dir: "/var/cache/enroot"
enroot_runtime_path: "/run/enroot"
enroot_temp_dir: "/tmp/"
# Pyxis build директория (временная, только для компиляции)
pyxis_build_dir: "/tmp/pyxis-build"

# ОФИЦИАЛЬНАЯ конфигурация SPANK
plugstack_config_dir: "/etc/slurm/plugstack.conf.d"

# =============================================================================
# ENROOT НАСТРОЙКИ
# =============================================================================

# Runtime настройки
enroot_mount_home: true
enroot_mount_tmp: true
pyxis_run_tmpfs_size: "16G"

# Storage mapping
enroot_bind_mounts:
  - "/home:/home"
  - "/sw:/sw"
  - "/opt/slurm:/opt/slurm:ro"

# GPU settings
enroot_restrict_dev: true
enroot_gpu_support: true
enroot_allow_privileged: true
enroot_allow_setuid: true

# Container registry settings
container_registry_default: "docker.io"
container_squashfs_support: true

# =============================================================================
# СИСТЕМНЫЕ ЗАВИСИМОСТИ
# =============================================================================

# Пакеты для Enroot
enroot_system_packages:
  - fuse3
  - squashfs-tools
  - parallel
  - curl
  - gzip
  - zstd
  - pigz
  - pv

# Build зависимости для Pyxis (минимальные)
pyxis_build_packages:
  - build-essential
  - pkg-config

# =============================================================================
# ПРОИЗВОДИТЕЛЬНОСТЬ И ЛИМИТЫ
# =============================================================================

# Limits
enroot_max_containers_per_user: 10
enroot_max_processors: "{{ ansible_processor_vcpus }}"
enroot_max_memory: "{{ (ansible_memtotal_mb * 0.8) | int }}M"

# Логирование
enroot_log_level: "INFO"
pyxis_log_level: "info"

# =============================================================================
# ПРОВЕРКИ
# =============================================================================

# Включить проверки после установки
containers_verify_installation: true
containers_test_nvidia_runtime: true

# =============================================================================
# УДАЛЕННЫЕ ПЕРЕМЕННЫЕ (больше не нужны!)
# =============================================================================

# ❌ pyxis_library_path - плагин устанавливается в /usr/local/lib/slurm/
# ❌ pyxis_spank_config - используется plugstack.conf.d/
# ❌ slurm_prolog_dir, slurm_epilog_dir - не нужны для базовой функциональности  
# ❌ enroot_prolog_enabled, enroot_epilog_enabled - упрощаем

# =============================================================================
# КОММЕНТАРИИ
# =============================================================================

# Этот файл настроен для официального подхода установки Pyxis:
# 1. make install - устанавливает плагин в /usr/local/lib/slurm/
# 2. готовый конфиг в /usr/local/share/pyxis/pyxis.conf
# 3. символическая ссылка в /etc/slurm/plugstack.conf.d/pyxis.conf
# 4. установка на compute И login узлы (согласно документации SPANK)