# roles/containers/defaults/main.yml
---
# =============================================================================
# КОНТЕЙНЕРЫ DEFAULTS (DEEPOPS ПОДХОД)
# =============================================================================

# Версии (DeepOps совместимые)
enroot_version: "3.5.0"
pyxis_version: "0.20.0"

# URLs
enroot_download_url: "https://github.com/NVIDIA/enroot/releases/download/v{{ enroot_version }}"
pyxis_git_repo: "https://github.com/NVIDIA/pyxis.git"

# =============================================================================
# ПУТИ (DEEPOPS СТАНДАРТ)
# =============================================================================

# Enroot пути
enroot_config_dir: "/etc/enroot"
enroot_data_dir: "/var/lib/enroot" 
enroot_cache_dir: "/var/cache/enroot"
enroot_runtime_path: "/run/enroot"

# Slurm integration paths (СИСТЕМНЫЕ ПАКЕТЫ!)
slurm_include_path: "/usr/include/slurm"
slurm_lib_path: "/usr/lib/x86_64-linux-gnu"
pyxis_install_path: "/usr/local/lib/slurm"

# SPANK configuration
spank_plugin_dir: "/usr/local/lib/slurm"
plugstack_config_path: "/etc/slurm/plugstack.conf"

# =============================================================================
# NVIDIA CONTAINER TOOLKIT
# =============================================================================

# NVIDIA settings
nvidia_container_toolkit_enabled: true
nvidia_container_runtime_enabled: true

# GPU detection
gpu_support_enabled: true
nvidia_visible_devices: "all"
nvidia_driver_capabilities: "compute,utility"

# =============================================================================
# ENROOT КОНФИГУРАЦИЯ (DEEPOPS ОПТИМИЗИРОВАННАЯ)
# =============================================================================

# Storage settings
enroot_squashfs_support: true
enroot_gzip_program: "pigz"

# Security (DeepOps defaults)
enroot_allow_privileged: true
enroot_allow_setuid: true
enroot_restrict_dev: false

# Mount настройки
enroot_mount_binds:
  - "/home:/home"
  - "/sw:/sw"
  - "/opt/slurm:/opt/slurm:ro"

# Runtime limits
enroot_max_containers_per_user: 100
enroot_max_processors: "{{ ansible_processor_vcpus | default(4) }}"
enroot_max_memory: "{{ ((ansible_memtotal_mb | default(8000)) * 0.8) | int }}M"

# Networking
enroot_mount_nvidia: true
enroot_mount_home: true

# =============================================================================
# СИСТЕМНЫЕ ПАКЕТЫ
# =============================================================================

# Основные зависимости (DeepOps список)
enroot_system_packages:
  - fuse3
  - squashfs-tools
  - parallel
  - curl
  - gzip
  - zstd
  - pigz
  - pv
  - jq

# Build зависимости для Pyxis
pyxis_build_packages:
  - build-essential
  - pkg-config
  - libslurm-dev  # UBUNTU СИСТЕМНЫЙ ПАКЕТ!
  - git

# NVIDIA пакеты
nvidia_packages:
  - nvidia-container-toolkit
  - nvidia-container-runtime

# =============================================================================
# ЛОГИРОВАНИЕ И ОТЛАДКА
# =============================================================================

# Logging levels
enroot_log_level: "INFO"
containers_debug_enabled: false

# Verification settings
containers_verify_installation: true
containers_run_tests: true

# =============================================================================
# DEEPOPS СПЕЦИФИЧНЫЕ НАСТРОЙКИ
# =============================================================================

# Use system packages where possible (DeepOps approach)
use_system_slurm_packages: true

# Build from source only when necessary
force_pyxis_rebuild: false

# Container registry settings
default_container_registry: "docker.io"

# Performance settings
enroot_parallel_downloads: true
enroot_cache_timeout: 3600

# =============================================================================
# ИНТЕГРАЦИЯ С SLURM
# =============================================================================

# SPANK plugin settings
spank_plugin_required: true
spank_plugin_load_type: "required"

# Slurm restart behavior
restart_slurm_after_install: true
slurm_restart_delay: 5

# =============================================================================
# ПРОВЕРКИ И ВАЛИДАЦИЯ
# =============================================================================

# Pre-installation checks
check_slurm_headers: true
check_gpu_availability: true
check_disk_space: true

# Post-installation tests
test_enroot_basic: true
test_pyxis_integration: true
test_container_run: true

# Test containers
test_containers:
  - "docker://hello-world"
  - "docker://ubuntu:22.04"

# =============================================================================
# TROUBLESHOOTING
# =============================================================================

# Debug settings
enable_debug_output: false
save_build_logs: true
build_log_dir: "/var/log/containers-build"

# Cleanup settings
cleanup_temp_files: true
cleanup_failed_builds: true

# =============================================================================
# КОММЕНТАРИИ
# =============================================================================

# Этот файл настроен для DeepOps подхода:
# 1. Использование системных пакетов Slurm вместо самостоятельной компиляции
# 2. Правильная установка NVIDIA Container Toolkit
# 3. Официальная компиляция Pyxis с правильными путями
# 4. DeepOps совместимые настройки безопасности и производительности
# 5. Надежная интеграция с systemd