---
galaxy_info:
  author: HPC Admin
  description: PMIx installation for HPC compute nodes
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - "20.04"
        - "22.04"
        - "24.04"
dependencies: []