# roles/common/tasks/network_tuning.yml - Network performance tuning for HPC
---
- name: "Apply network performance sysctl settings"
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/99-hpc-network.conf
  loop:
    - { key: "net.core.rmem_max", value: "268435456" }
    - { key: "net.core.wmem_max", value: "268435456" }
    - { key: "net.ipv4.tcp_rmem", value: "4096 65536 268435456" }
    - { key: "net.ipv4.tcp_wmem", value: "4096 65536 268435456" }
    - { key: "net.core.netdev_max_backlog", value: "30000" }
    - { key: "net.core.netdev_budget", value: "600" }
    - { key: "net.ipv4.tcp_congestion_control", value: "bbr" }
    - { key: "net.ipv4.tcp_mtu_probing", value: "1" }

- name: "Disable swap for HPC performance"
  command: swapoff -a
  ignore_errors: yes

- name: "Disable swap in fstab"
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
    backup: yes

- name: "Configure systemd limits for HPC"
  blockinfile:
    path: /etc/systemd/system.conf
    backup: yes
    block: |
      DefaultLimitNOFILE=131072
      DefaultLimitNPROC=65536
      DefaultLimitMEMLOCK=infinity
      DefaultLimitSTACK=8388608
    marker: "# {mark} ANSIBLE MANAGED BLOCK - HPC LIMITS"
  notify: reload systemd