
# roles/containers/meta/main.yml
---
# Роль: containers - метаданные

galaxy_info:
  author: DevOps Team
  description: Enroot + Pyxis container support for Slurm HPC cluster
  company: HPC Lab
  license: MIT
  min_ansible_version: 2.15
  
  platforms:
    - name: Ubuntu
      versions:
        - 24.04

  galaxy_tags:
    - hpc
    - slurm
    - containers
    - enroot
    - pyxis
    - nvidia
    - gpu

# Зависимости роли
dependencies:
  - role: common
    # Базовая настройка узла - MUNGE, NFS, пользователи

# Роль выполняется на всех compute и gpu узлах
allow_duplicates: false