---
# Переменные по умолчанию для роли slurm_build

# =============================================================================
# ВЕРСИИ И ПУТИ
# =============================================================================

# Версия Slurm (берется из общих переменных, но можно переопределить)
slurm_version: "25.05.1"
slurm_download_url: "https://download.schedmd.com/slurm/slurm-{{ slurm_version }}.tar.bz2"

# Пути для сборки и установки
slurm_build_dir: "/tmp/slurm-build"
slurm_install_prefix: "/opt/slurm"  # Изменил с /usr/local на /opt/slurm

# =============================================================================
# ПАРАМЕТРЫ СБОРКИ
# =============================================================================

# Опции конфигурации Slurm
slurm_configure_options:
  - "--prefix={{ slurm_install_prefix }}"
  - "--sysconfdir=/etc/slurm"
  - "--enable-pam"
  - "--with-pam_dir=/lib/x86_64-linux-gnu/security/"
  - "--without-shared-libslurm"
  - "--with-pmix"
  - "--with-systemd"
  - "--with-jwt"
  - "--with-mysql_config=/usr/bin/mariadb_config"
  - "--with-munge=/usr"
  - "--with-hwloc"
  - "--enable-slurmrestd"
  - "--enable-x11"

# Количество ядер для компиляции (автоопределение через nproc)
slurm_make_jobs: "$(nproc)"

# =============================================================================
# БИНАРНИКИ SLURM
# =============================================================================

# Пользовательские команды Slurm
slurm_user_commands:
  - sinfo
  - squeue
  - scancel
  - sbatch
  - salloc
  - srun
  - sacct
  - scontrol
  - sprio
  - smap
  - sdiag
  - sstat
  - sreport
  - sacctmgr

# Демоны Slurm
slurm_daemons:
  - slurmctld
  - slurmd
  - slurmdbd
  - slurmrestd

# Дополнительные утилиты
slurm_additional_tools:
  - sshare
  - sjstat
  - squeue
  - strigger

# =============================================================================
# ЗАВИСИМОСТИ СБОРКИ (исправлено для Ubuntu 24.04)
# =============================================================================

# Основные зависимости сборки 
slurm_build_dependencies:
  # Основные компиляторы и утилиты
  - build-essential
  - libmunge-dev
  - pkg-config
  # MariaDB/MySQL (исправлено для Ubuntu 24.04)
  - libmariadb-dev
  - mariadb-client
  # JSON и JWT поддержка  
  - libjson-c-dev
  - libjwt-dev
  - libhttp-parser-dev
  - libyaml-dev
  # SSL и безопасность
  - libssl-dev
  - libcurl4-openssl-dev
  # NVIDIA GPU поддержка (КРИТИЧНО!)
  - libnvidia-ml-dev
  # PAM и системная интеграция
  - libpam0g-dev
  - libdbus-1-dev
  - libsystemd-dev
  # Дополнительные библиотеки
  - libhwloc-dev
  - libpmix-dev
  - libncurses-dev
  - libreadline-dev
  - librrd-dev
  - liblua5.3-dev
  - libperl-dev
  - libgtk2.0-dev
  # Утилиты
  - python3-dev
  - python3-minimal
  - ruby-dev
  - wget
  - man2html-base
  - bash-completion

# =============================================================================
# ПРОВЕРКИ И ВАЛИДАЦИЯ
# =============================================================================

# Проверять ли сборку после компиляции
slurm_verify_build: true

# Создавать ли резервную копию старой версии
slurm_backup_old_version: true

# Очищать ли временные файлы после сборки
slurm_cleanup_build_dir: false

# =============================================================================
# РАСПРОСТРАНЕНИЕ
# =============================================================================

# Метод распространения: archive, rsync, nfs
slurm_distribution_method: "archive"

# Таймаут для операций копирования (секунды)
slurm_copy_timeout: 600