# roles/slurm_build/defaults/main.yml - Slurm build configuration variables
---

# Version and paths
slurm_version: "25.05.1"
slurm_download_url: "https://download.schedmd.com/slurm/slurm-{{ slurm_version }}.tar.bz2"
slurm_build_dir: "/tmp/slurm-build"
slurm_install_prefix: "/opt/slurm"

# Build parameters
slurm_configure_options:
  - "--prefix={{ slurm_install_prefix }}"
  - "--sysconfdir=/etc/slurm"
  - "--enable-pam"
  - "--with-pam_dir=/lib/x86_64-linux-gnu/security/"
  - "--without-shared-libslurm"
  - "--with-pmix=/opt/pmix"
  - "--with-systemd"
  - "--with-jwt"
  - "--with-mysql_config=/usr/bin/mariadb_config"
  - "--with-munge=/usr"
  - "--with-hwloc"
  - "--enable-slurmrestd"
  - "--enable-x11"

slurm_make_jobs: "$(nproc)"

# Slurm binaries
slurm_force_rebuild: false
slurm_user_commands:
  - sinfo
  - squeue
  - scancel
  - sbatch
  - salloc
  - srun
  - sacct
  - scontrol
  - sprio
  - smap
  - sdiag
  - sstat
  - sreport
  - sacctmgr

slurm_daemons:
  - slurmctld
  - slurmd
  - slurmdbd
  - slurmrestd

# Build dependencies 
slurm_build_dependencies:
  - build-essential
  - libmunge-dev
  - pkg-config
  - libmariadb-dev
  - mariadb-client
  - libjson-c-dev
  - libjwt-dev
  - libhttp-parser-dev
  - libyaml-dev
  - libssl-dev
  - libcurl4-openssl-dev
  - libnvidia-ml-dev
  - libpam0g-dev
  - libdbus-1-dev
  - libsystemd-dev
  - libhwloc-dev
  - libncurses-dev
  - libreadline-dev
  - librrd-dev
  - liblua5.3-dev
  - libperl-dev
  - libgtk2.0-dev
  - python3-dev
  - python3-minimal
  - ruby-dev
  - wget
  - man2html-base
  - bash-completion

# Verification and cleanup
slurm_verify_build: true
slurm_backup_old_version: true
slurm_cleanup_build_dir: false

# Distribution
slurm_distribution_method: "archive"
slurm_copy_timeout: 600