# roles/slurm_compute/tasks/main.yml
---
# =============================================================================
# SLURM COMPUTE NODE CONFIGURATION
# =============================================================================

- name: "[SLURM-COMPUTE] Начало настройки Slurm Compute узла"
  debug:
    msg: |
      🎯 Настройка Slurm Compute узла: {{ inventory_hostname }}
      🔗 Master: {{ slurm_master_host }} ({{ slurm_master_addr }})
      🖥️  GPU: {{ gpu_count }}x {{ gpu_type }}

# =============================================================================
# УСТАНОВКА SLURM BINARIES
# =============================================================================

- name: "[SLURM-COMPUTE] Проверка доступности Slurm binaries"
  stat:
    path: "/opt/slurm/sbin/slurmd"
  register: slurmd_binary
  tags: verify

- name: "[SLURM-COMPUTE] Копирование Slurm binaries из NFS"
  shell: |
    cp -r /sw/slurm-final/* /opt/slurm/
    chown -R root:root /opt/slurm
    chmod -R 755 /opt/slurm/bin /opt/slurm/sbin
    echo "✅ Slurm скопирован на {{ inventory_hostname }}"
  when: not slurmd_binary.stat.exists
  tags: install

- name: "[SLURM-COMPUTE] Проверка доступности мастер узла"
  wait_for:
    host: "{{ slurm_master_addr }}"
    port: 6817
    timeout: 10
  ignore_errors: true
  register: master_connectivity
  tags: verify

- name: "[SLURM-COMPUTE] Предупреждение о мастер узле"
  debug:
    msg: |
      ⚠️  Мастер узел {{ slurm_master_host }}:6817 недоступен
      🔧 Продолжаем настройку, но slurmd может не запуститься
  when: master_connectivity.failed | default(false)
  tags: verify

# =============================================================================
# КОПИРОВАНИЕ КОНФИГУРАЦИОННЫХ ФАЙЛОВ
# =============================================================================

- name: "[SLURM-COMPUTE] Ожидание конфигурационных файлов на NFS"
  wait_for:
    path: "{{ nfs_config_path }}/{{ item }}"
    timeout: 30
  loop: "{{ slurm_config_files }}"
  tags: config

- name: "[SLURM-COMPUTE] Копирование конфигурационных файлов из NFS"
  copy:
    src: "{{ nfs_config_path }}/{{ item }}"
    dest: "{{ slurm_config_dir }}/{{ item }}"
    remote_src: yes
    owner: slurm
    group: slurm
    mode: '0644'
    backup: yes
  loop: "{{ slurm_config_files }}"
  notify: restart slurmd
  tags: config

# =============================================================================
# КОПИРОВАНИЕ PROLOG/EPILOG СКРИПТОВ
# =============================================================================

- name: "[SLURM-COMPUTE] Создание директорий для prolog/epilog"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /etc/slurm/prolog.d
    - /etc/slurm/epilog.d

- name: "[SLURM-COMPUTE] Ожидание prolog/epilog скриптов на NFS"
  wait_for:
    path: "{{ nfs_config_path }}/{{ item }}"
    timeout: 30
  loop:
    - prolog.sh
    - epilog.sh

- name: "[SLURM-COMPUTE] Копирование prolog/epilog скриптов из NFS"
  copy:
    src: "{{ nfs_config_path }}/{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
    owner: root
    group: root
    mode: '0755'
    backup: yes
  loop:
    - { src: "prolog.sh", dest: "/etc/slurm/prolog.d/prolog.sh" }
    - { src: "epilog.sh", dest: "/etc/slurm/epilog.d/epilog.sh" }
  notify: restart slurmd

- name: "[SLURM-COMPUTE] Создание символических ссылок на команды"
  file:
    src: "/opt/slurm/bin/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
    force: yes
  loop:
    - sinfo
    - squeue
    - sbatch
    - srun
    - scancel
    - scontrol
  tags: links

- name: "[SLURM-COMPUTE] Создание символических ссылок на демоны"
  file:
    src: "/opt/slurm/sbin/{{ item }}"
    dest: "/usr/sbin/{{ item }}"
    state: link
    force: yes
  loop:
    - slurmd
  tags: links

# =============================================================================
# GPU DETECTION (если включено)
# =============================================================================

- name: "[SLURM-COMPUTE] Проверка наличия NVIDIA GPU"
  command: nvidia-smi -L
  register: nvidia_check
  failed_when: false
  changed_when: false
  when: gpu_detection_enabled
  tags: gpu

- name: "[SLURM-COMPUTE] Результат обнаружения GPU"
  debug:
    msg: |
      {% if nvidia_check.rc == 0 %}
      🎮 GPU обнаружены:
      {{ nvidia_check.stdout_lines | join('\n') }}
      {% else %}
      ⚠️  GPU не обнаружены или nvidia-smi недоступен
      📝 Будет использоваться конфигурация по умолчанию
      {% endif %}
  when: gpu_detection_enabled
  tags: gpu

# =============================================================================
# SYSTEMD SERVICE CONFIGURATION
# =============================================================================

- name: "[SLURM-COMPUTE] Создание systemd unit для slurmd"
  template:
    src: slurmd.service.j2
    dest: /etc/systemd/system/slurmd.service
    owner: root
    group: root
    mode: '0644'
  notify: restart slurmd
  tags: service

- name: "[SLURM-COMPUTE] Перезагрузка systemd daemon"
  systemd:
    daemon_reload: yes
  tags: service

# =============================================================================
# CGROUP CONFIGURATION
# =============================================================================

- name: "[SLURM-COMPUTE] Проверка cgroup v1/v2"
  shell: |
    if [ -d /sys/fs/cgroup/systemd ]; then
      echo "cgroup_v1"
    elif [ -f /sys/fs/cgroup/cgroup.controllers ]; then
      echo "cgroup_v2"
    else
      echo "unknown"
    fi
  register: cgroup_version
  changed_when: false
  when: cgroup_enabled
  tags: cgroup

- name: "[SLURM-COMPUTE] Информация о cgroup"
  debug:
    msg: |
      🗂️  Cgroup версия: {{ cgroup_version.stdout | default('не определена') }}
      📁 Точка монтирования: /sys/fs/cgroup
  when: cgroup_enabled
  tags: cgroup

# =============================================================================
# NODE HEALTH CHECK
# =============================================================================

- name: "[SLURM-COMPUTE] Создание скрипта проверки здоровья узла"
  copy:
    dest: /usr/local/bin/slurm_health_check.sh
    mode: '0755'
    content: |
      #!/bin/bash
      # Slurm Node Health Check Script
      # Generated by Ansible
      
      # Check disk space
      DISK_USAGE=$(df / | tail -1 | awk '{print $5}' | sed 's/%//')
      if [ $DISK_USAGE -gt 90 ]; then
        echo "ERROR: Disk usage is ${DISK_USAGE}%"
        exit 1
      fi
      
      # Check memory
      MEM_AVAILABLE=$(free | awk '/^Mem:/{print int($7/$2*100)}')
      if [ $MEM_AVAILABLE -lt 5 ]; then
        echo "ERROR: Memory usage too high, only ${MEM_AVAILABLE}% available"
        exit 1
      fi
      
      # Check GPU (if present)
      if command -v nvidia-smi >/dev/null 2>&1; then
        if ! nvidia-smi -q >/dev/null 2>&1; then
          echo "ERROR: GPU check failed"
          exit 1
        fi
      fi
      
      echo "Node {{ inventory_hostname }} is healthy"
      exit 0
  tags: health

# =============================================================================
# SERVICE STARTUP
# =============================================================================

- name: "[SLURM-COMPUTE] Запуск и включение slurmd"
  systemd:
    name: slurmd
    enabled: "{{ slurmd_service_enabled }}"
    state: "{{ slurmd_auto_start | ternary('started', 'stopped') }}"
  tags: service

# =============================================================================
# VERIFICATION
# =============================================================================

- name: "[SLURM-COMPUTE] Пауза перед проверкой"
  pause:
    seconds: 5
  tags: verify

- name: "[SLURM-COMPUTE] Проверка статуса slurmd"
  systemd:
    name: slurmd
  register: slurmd_status
  tags: verify

- name: "[SLURM-COMPUTE] Проверка логов slurmd"
  shell: |
    if systemctl is-active slurmd >/dev/null 2>&1; then
      echo "✅ slurmd активен"
      tail -3 {{ slurmd_log_file }} 2>/dev/null || echo "Логи пока недоступны"
    else
      echo "❌ slurmd неактивен"
      journalctl -u slurmd -n 5 --no-pager
    fi
  register: slurmd_check
  changed_when: false
  tags: verify

- name: "[SLURM-COMPUTE] Тест подключения к мастеру"
  shell: |
    # Попробуем подключиться к slurmctld
    timeout 10 telnet {{ slurm_master_addr }} 6817 </dev/null >/dev/null 2>&1
    if [ $? -eq 0 ]; then
      echo "✅ Подключение к мастеру работает"
    else
      echo "⚠️  Подключение к мастеру недоступно"
    fi
  register: master_connection_test
  failed_when: false
  changed_when: false
  tags: verify
