# playbooks/containers.yml
---
# =============================================================================
# РАЗВЕРТЫВАНИЕ КОНТЕЙНЕРНОЙ ПОДДЕРЖКИ (ENROOT + PYXIS)
# =============================================================================

- name: "🐳 Установка контейнерной поддержки"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "📋 Информация о контейнеризации"
      debug:
        msg: |
          ================================================================================
          🐳 УСТАНОВКА КОНТЕЙНЕРНОЙ ПОДДЕРЖКИ
          ================================================================================
          🔧 Компоненты: Enroot + Pyxis + NVIDIA Container Toolkit
          🎯 Целевые узлы: {{ groups['slurm_cluster'] | length }}
          🎮 GPU узлы: {{ groups['gpu_nodes'] | default([]) | length }}
          
          📊 Узлы для установки:
          🖥️  Compute: {{ groups['slurm_compute'] | join(', ') }}
          🔑 Login:   {{ groups['slurm_login'] | join(', ') }}
          🎛️  Master:  {{ groups['slurm_master'] | join(', ') }}
          
          ⏱️  Ожидаемое время: ~20-30 минут
          ================================================================================

# =============================================================================
# УСТАНОВКА НА ВСЕ УЗЛЫ КЛАСТЕРА
# =============================================================================

- name: "🐳 Этап 1/3: Установка Enroot на все узлы"
  hosts: slurm_cluster
  become: true
  gather_facts: true
  tasks:
    - name: "📋 Информация об узле"
      debug:
        msg: |
          🐳 Установка контейнеров на {{ inventory_hostname }}
          🔧 Роль: {{ 'GPU' if inventory_hostname in groups['gpu_nodes'] | default([]) else 'CPU' }}
          💾 RAM: {{ (ansible_memtotal_mb / 1024) | round(1) }}GB
      run_once: false

  roles:
    - containers

  post_tasks:
    - name: "✅ Результат установки"
      debug:
        msg: |
          ✅ Контейнеры установлены на {{ inventory_hostname }}
          🐳 Enroot: готов
          🔌 Pyxis: {{ 'установлен' if inventory_hostname in groups['slurm_compute'] else 'не требуется' }}
          🎮 NVIDIA: {{ 'настроено' if inventory_hostname in groups['gpu_nodes'] | default([]) else 'не требуется' }}

# =============================================================================
# ОБНОВЛЕНИЕ SLURM КОНФИГУРАЦИИ
# =============================================================================

- name: "🐳 Этап 2/3: Обновление Slurm конфигурации"
  hosts: slurm_master
  become: true
  tasks:
    - name: "📝 Добавление поддержки контейнеров в slurm.conf"
      lineinfile:
        path: /etc/slurm/slurm.conf
        regexp: '^#?TaskPlugin='
        line: 'TaskPlugin=task/cgroup,task/affinity'
        backup: yes
      notify: restart slurmctld

    - name: "📝 Обновление конфигурации в NFS"
      copy:
        src: /etc/slurm/slurm.conf
        dest: /sw/config/slurm.conf
        remote_src: yes
        owner: slurm
        group: slurm
        mode: '0644'

    - name: "🔄 Перезапуск slurmctld для применения изменений"
      systemd:
        name: slurmctld
        state: restarted

  handlers:
    - name: restart slurmctld
      systemd:
        name: slurmctld
        state: restarted

# =============================================================================
# ТЕСТИРОВАНИЕ КОНТЕЙНЕРОВ
# =============================================================================

- name: "🐳 Этап 3/3: Тестирование контейнерной поддержки"
  hosts: slurm_master
  become: true
  tasks:
    - name: "🧪 Комплексное тестирование контейнеров"
      shell: |
        echo "================================================================================"
        echo "🧪 ТЕСТИРОВАНИЕ КОНТЕЙНЕРНОЙ ПОДДЕРЖКИ"
        echo "================================================================================"
        echo ""
        
        echo "🐳 Тест базового контейнера:"
        timeout 300 srun -N1 --container-image=docker://hello-world || echo "Базовый тест не прошел"
        echo ""
        
        echo "🐧 Тест Ubuntu контейнера:"
        timeout 300 srun -N1 --container-image=docker://ubuntu:22.04 /bin/bash -c "uname -a && echo 'Ubuntu контейнер работает!'" || echo "Ubuntu тест не прошел"
        echo ""
        
        {% if groups['gpu_nodes'] | default([]) | length > 0 %}
        echo "🎮 Тест GPU контейнера:"
        timeout 300 srun -N1 --container-image=nvcr.io/nvidia/cuda:12.3-runtime-ubuntu22.04 nvidia-smi || echo "GPU тест не прошел"
        echo ""
        {% endif %}
        
        echo "📊 Статус узлов после установки:"
        sinfo -N
        echo ""
        
        echo "📋 Доступные образы:"
        enroot list 2>/dev/null || echo "Нет предзагруженных образов"
        echo ""
        
        echo "================================================================================"
      register: container_tests
      failed_when: false
      changed_when: false

- name: "🎉 ФИНАЛЬНЫЙ ОТЧЕТ ПО КОНТЕЙНЕРИЗАЦИИ"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "📊 Результаты контейнеризации"
      debug:
        msg: |
          ================================================================================
          🎉 КОНТЕЙНЕРИЗАЦИЯ ЗАВЕРШЕНА!
          ================================================================================
          
          📊 РЕЗУЛЬТАТЫ ТЕСТИРОВАНИЯ:
          {{ hostvars[groups['slurm_master'][0]]['container_tests']['stdout'] }}
          
          ================================================================================
          ✅ КЛАСТЕР ГОТОВ ДЛЯ КОНТЕЙНЕРОВ!
          ================================================================================
          
          🐳 Использование контейнеров:
          
          # Простой контейнер
          srun --container-image=docker://ubuntu:22.04 hostname
          
          # Python/AI контейнер
          srun --container-image=nvcr.io/nvidia/pytorch:23.12-py3 python --version
          
          {% if groups['gpu_nodes'] | default([]) | length > 0 %}
          # GPU контейнер
          srun --gres=gpu:1 --container-image=nvcr.io/nvidia/cuda:12.3-runtime-ubuntu22.04 nvidia-smi
          
          # PyTorch с GPU
          srun --gres=gpu:1 --container-image=nvcr.io/nvidia/pytorch:23.12-py3 python -c "import torch; print(torch.cuda.is_available())"
          {% endif %}
          
          # Интерактивный контейнер
          srun --pty --container-image=docker://ubuntu:22.04 /bin/bash
          
          # Batch job с контейнером
          sbatch --container-image=nvcr.io/nvidia/pytorch:23.12-py3 my_script.py
          
          🔧 Административные команды:
          - enroot list                    # Список образов
          - enroot import docker://image   # Импорт образа  
          - enroot create image            # Создание контейнера
          
          ================================================================================