# fix_enroot_unprivileged.yml
---
# =============================================================================
# ФИНАЛЬНОЕ РЕШЕНИЕ: ENROOT ДЛЯ UNPRIVILEGED ПОЛЬЗОВАТЕЛЕЙ
# =============================================================================
# Основано на продакшн конфигурации + DeepOps + Pyxis Wiki

- name: "🎯 ФИНАЛЬНОЕ ИСПРАВЛЕНИЕ: Enroot для обычных пользователей"
  hosts: slurm_cluster
  become: true
  gather_facts: false
  
  tasks:
    - name: "📋 Информация о финальном исправлении"
      debug:
        msg: |
          🎯 ФИНАЛЬНОЕ ИСПРАВЛЕНИЕ ENROOT
          ================================
          ✅ Основано на продакшн конфигурации
          ✅ Пользователь-специфичные пути
          ✅ Prolog/Epilog скрипты как в DeepOps
          ✅ Работает без root привилегий
          ================================

# =============================================================================
# ЭТАП 1: ПРАВИЛЬНАЯ КОНФИГУРАЦИЯ ENROOT
# =============================================================================

    - name: "📝 Создание ПРОДАКШН конфигурации enroot.conf"
      copy:
        dest: /etc/enroot/enroot.conf
        content: |
          # Enroot Configuration - PRODUCTION SETUP
          # Based on NVIDIA/pyxis wiki + real production deployment
          
          # =============================================================================
          # USER-SPECIFIC PATHS (ключ к решению!)
          # =============================================================================
          
          # Runtime path - per user (как в проде)
          ENROOT_RUNTIME_PATH /run/enroot/user-$(id -u)
          
          # Cache path - per group (экономия места)
          ENROOT_CACHE_PATH /var/lib/enroot-cache/group-$(id -g)
          
          # Data path - per user (изоляция)
          ENROOT_DATA_PATH /tmp/enroot-data/user-$(id -u)
          
          # =============================================================================
          # UNPRIVILEGED SETTINGS
          # =============================================================================
          
          # НЕ монтировать home по умолчанию
          ENROOT_MOUNT_HOME n
          
          # Ограничить доступ к устройствам  
          ENROOT_RESTRICT_DEV y
          
          # Разрешить запись в контейнер
          ENROOT_ROOTFS_WRITABLE y
          
          # НЕ делать пользователя root'ом в контейнере (КЛЮЧЕВОЕ!)
          ENROOT_REMAP_ROOT n
          
          # =============================================================================
          # PERFORMANCE SETTINGS
          # =============================================================================
          
          # Отключить сжатие для скорости
          ENROOT_SQUASH_OPTIONS -noI -noD -noF -noX -no-duplicates
          
          # Разрешить superuser только для установки пакетов
          ENROOT_ALLOW_SUPERUSER n
          
          # =============================================================================
          # МOUNTING НАСТРОЙКИ
          # =============================================================================
          
          # Дополнительные монтирования (опционально)
          # ENROOT_MOUNT_HOME /home:/home
          # ENROOT_MOUNT_HOME /sw:/sw
        owner: root
        group: root
        mode: '0644'
        backup: yes

# =============================================================================
# ЭТАП 2: PROLOG СКРИПТ (создание директорий как в проде)
# =============================================================================

    - name: "📁 Создание директории для prolog скриптов"
      file:
        path: /etc/slurm/prolog.d
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: "📝 Создание Prolog скрипта для Enroot (как в проде)"
      copy:
        dest: /etc/slurm/prolog.d/50-all-enroot-dirs
        content: |
          #!/usr/bin/env bash
          # Slurm Prolog: Create Enroot directories for unprivileged users
          # Based on production configuration from DeepOps
          
          set -ex
          
          # Проверяем наличие enroot
          command -v enroot >/dev/null || exit 0
          
          # Логирование
          logger -s -t slurm-prolog-enroot "Creating enroot dirs for user=$SLURM_JOB_USER job=$SLURM_JOB_ID"
          
          # =============================================================================
          # RUNTIME PATH - пользователь-специфичный
          # =============================================================================
          
          runtime_path="$(sudo -u "$SLURM_JOB_USER" sh -c 'echo "/run/enroot/user-$(id -u)"')"
          mkdir -p "$runtime_path"
          chown "$SLURM_JOB_UID:$(id -g "$SLURM_JOB_UID")" "$runtime_path"
          chmod 0755 "$(dirname "$runtime_path")" 2>/dev/null || true
          chmod 0700 "$runtime_path"
          
          # =============================================================================
          # CACHE PATH - групповой (экономия места)
          # =============================================================================
          
          cache_path="$(sudo -u "$SLURM_JOB_USER" sh -c 'echo "/var/lib/enroot-cache/group-$(id -g)"')"
          mkdir -p "$cache_path"
          chown "$SLURM_JOB_UID:$(id -g "$SLURM_JOB_UID")" "$cache_path"
          chmod 0770 "$cache_path"
          
          # =============================================================================
          # DATA PATH - пользователь-специфичный
          # =============================================================================
          
          data_path="$(sudo -u "$SLURM_JOB_USER" sh -c 'echo "/tmp/enroot-data/user-$(id -u)"')"
          mkdir -p "$data_path"
          chown "$SLURM_JOB_UID:$(id -g "$SLURM_JOB_UID")" "$data_path"
          chmod 0700 "$data_path"
          
          logger -s -t slurm-prolog-enroot "Created: runtime=$runtime_path cache=$cache_path data=$data_path"
        owner: root
        group: root
        mode: '0755'

# =============================================================================
# ЭТАП 3: EPILOG СКРИПТ (очистка как в проде)
# =============================================================================

    - name: "📁 Создание директории для epilog скриптов"
      file:
        path: /etc/slurm/epilog.d
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: "📝 Создание Epilog скрипта для Enroot (как в проде)"
      copy:
        dest: /etc/slurm/epilog.d/50-lastuserjob-all-enroot-dirs
        content: |
          #!/usr/bin/env bash
          # Slurm Epilog: Cleanup Enroot directories for unprivileged users
          # Based on production configuration from DeepOps
          
          set -ex
          
          # Проверяем наличие enroot
          command -v enroot >/dev/null || exit 0
          
          # Логирование
          logger -s -t slurm-epilog-enroot "Cleaning enroot dirs for user=$SLURM_JOB_USER job=$SLURM_JOB_ID"
          
          # =============================================================================
          # ОЧИСТКА RUNTIME PATH
          # =============================================================================
          
          runtime_path="$(sudo -u "$SLURM_JOB_USER" sh -c 'echo "/run/enroot/user-$(id -u)"')"
          if [ -d "$runtime_path" ]; then
            rm -rf "$runtime_path"
            logger -s -t slurm-epilog-enroot "Cleaned runtime: $runtime_path"
          fi
          
          # =============================================================================
          # ОЧИСТКА DATA PATH (НЕ трогаем cache - он общий)
          # =============================================================================
          
          data_path="$(sudo -u "$SLURM_JOB_USER" sh -c 'echo "/tmp/enroot-data/user-$(id -u)"')"
          if [ -d "$data_path" ]; then
            rm -rf "$data_path"
            logger -s -t slurm-epilog-enroot "Cleaned data: $data_path"
          fi
        owner: root
        group: root
        mode: '0755'

# =============================================================================
# ЭТАП 4: ОСНОВНЫЕ PROLOG/EPILOG СКРИПТЫ
# =============================================================================

    - name: "📝 Создание основного prolog скрипта"
      copy:
        dest: /etc/slurm/prolog.sh
        content: |
          #!/usr/bin/env bash
          # Main Slurm Prolog Script
          
          set -e
          
          logger -s -t slurm-prolog "START user=$SLURM_JOB_USER job=$SLURM_JOB_ID"
          
          # Запуск всех prolog скриптов
          if [ -d /etc/slurm/prolog.d ]; then
            for script in /etc/slurm/prolog.d/*; do
              if [ -x "$script" ]; then
                logger -s -t slurm-prolog "Running $script"
                "$script"
              fi
            done
          fi
          
          logger -s -t slurm-prolog "END user=$SLURM_JOB_USER job=$SLURM_JOB_ID"
        owner: root
        group: root
        mode: '0755'

    - name: "📝 Создание основного epilog скрипта"
      copy:
        dest: /etc/slurm/epilog.sh
        content: |
          #!/usr/bin/env bash
          # Main Slurm Epilog Script
          
          set -e
          
          logger -s -t slurm-epilog "START user=$SLURM_JOB_USER job=$SLURM_JOB_ID"
          
          # Запуск всех epilog скриптов
          if [ -d /etc/slurm/epilog.d ]; then
            for script in /etc/slurm/epilog.d/*; do
              if [ -x "$script" ]; then
                logger -s -t slurm-epilog "Running $script"
                "$script"
              fi
            done
          fi
          
          logger -s -t slurm-epilog "END user=$SLURM_JOB_USER job=$SLURM_JOB_ID"
        owner: root
        group: root
        mode: '0755'

# =============================================================================
# ЭТАП 5: ОБНОВЛЕНИЕ SLURM КОНФИГУРАЦИИ
# =============================================================================

    - name: "📝 Добавление Prolog/Epilog в slurm.conf"
      lineinfile:
        path: /etc/slurm/slurm.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backup: yes
      loop:
        - { regexp: '^#?Prolog=', line: 'Prolog=/etc/slurm/prolog.sh' }
        - { regexp: '^#?Epilog=', line: 'Epilog=/etc/slurm/epilog.sh' }
      when: inventory_hostname in groups['slurm_master']

    - name: "📤 Копирование обновленной конфигурации в NFS"
      copy:
        src: /etc/slurm/slurm.conf
        dest: /sw/config/slurm.conf
        remote_src: yes
        owner: slurm
        group: slurm
        mode: '0644'
      when: inventory_hostname in groups['slurm_master']

    - name: "📥 Копирование обновленной конфигурации на другие узлы"
      copy:
        src: /sw/config/slurm.conf
        dest: /etc/slurm/slurm.conf
        remote_src: yes
        owner: slurm
        group: slurm
        mode: '0644'
        backup: yes
      when: inventory_hostname not in groups['slurm_master']

# =============================================================================
# ЭТАП 6: ПЕРЕЗАПУСК СЕРВИСОВ
# =============================================================================

    - name: "🔄 Перезапуск slurmctld на master"
      systemd:
        name: slurmctld
        state: restarted
      when: inventory_hostname in groups['slurm_master']

    - name: "🔄 Перезапуск slurmd на compute узлах"
      systemd:
        name: slurmd
        state: restarted
      when: inventory_hostname in groups['slurm_compute']

    - name: "⏰ Пауза после перезапуска"
      pause:
        seconds: 5

# =============================================================================
# ЭТАП 7: ФИНАЛЬНОЕ ТЕСТИРОВАНИЕ
# =============================================================================

- name: "🧪 ФИНАЛЬНЫЙ ТЕСТ: Контейнеры для обычных пользователей"
  hosts: slurm_master
  become: false  # ❗ КРИТИЧНО - тестируем от обычного пользователя!
  tasks:
    - name: "🧪 Тест контейнера от обычного пользователя"
      shell: |
        echo "🧪 ФИНАЛЬНЫЙ ТЕСТ ENROOT ДЛЯ ОБЫЧНЫХ ПОЛЬЗОВАТЕЛЕЙ"
        echo "Пользователь: $(whoami) (UID: $(id -u))"
        echo "Дата: $(date)"
        echo ""
        
        echo "=== ПРОВЕРКА ENROOT КОНФИГУРАЦИИ ==="
        echo "ENROOT_RUNTIME_PATH должен быть: /run/enroot/user-$(id -u)"
        echo "ENROOT_CACHE_PATH должен быть: /var/lib/enroot-cache/group-$(id -g)"
        echo "ENROOT_DATA_PATH должен быть: /tmp/enroot-data/user-$(id -u)"
        echo ""
        
        echo "=== ТЕСТ ПРОСТОГО КОНТЕЙНЕРА ==="
        timeout 120 srun --container-image=docker://hello-world 2>&1
        echo ""
        
        echo "=== ТЕСТ UBUNTU КОНТЕЙНЕРА ==="
        timeout 120 srun --container-image=docker://ubuntu:22.04 /bin/bash -c "whoami && id && echo 'SUCCESS: Ubuntu контейнер работает для обычного пользователя!'" 2>&1
        echo ""
        
        echo "=== ПРОВЕРКА ДИРЕКТОРИЙ ПОСЛЕ ЗАДАЧИ ==="
        echo "Пользовательские директории должны быть очищены epilog скриптом"
        ls -la /run/enroot/ 2>/dev/null || echo "Директория /run/enroot не существует (это нормально)"
        ls -la /tmp/enroot-data/ 2>/dev/null || echo "Директория /tmp/enroot-data не существует (это нормально)"
        echo ""
        
      register: final_test
      failed_when: false

    - name: "🎉 РЕЗУЛЬТАТ ФИНАЛЬНОГО ТЕСТА"
      debug:
        msg: |
          ===============================================================================
          🎯 РЕЗУЛЬТАТ ФИНАЛЬНОГО ТЕСТА ENROOT ДЛЯ ОБЫЧНЫХ ПОЛЬЗОВАТЕЛЕЙ:
          ===============================================================================
          
          {{ final_test.stdout }}
          
          {% if 'SUCCESS: Ubuntu контейнер работает для обычного пользователя!' in final_test.stdout %}
          🎉🎉🎉 ПОЛНАЯ ПОБЕДА! ENROOT РАБОТАЕТ ДЛЯ ОБЫЧНЫХ ПОЛЬЗОВАТЕЛЕЙ! 🎉🎉🎉
          
          ✅ Контейнеры запускаются без root
          ✅ Пользователь-специфичные пути работают  
          ✅ Prolog создает директории с правильными правами
          ✅ Epilog очищает пользовательские данные
          ✅ Продакшн конфигурация применена успешно
          
          📋 КОМАНДЫ ДЛЯ ПОЛЬЗОВАТЕЛЕЙ:
          - srun --container-image=docker://ubuntu:22.04 hostname
          - srun --pty --container-image=docker://ubuntu:22.04 bash
          - sbatch --container-image=nvcr.io/nvidia/pytorch:latest script.py
          
          🚀 КЛАСТЕР ГОТОВ К ПРОДАКШЕНУ БЕЗ ROOT!
          
          {% elif 'Hello from Docker' in final_test.stdout %}
          🎉🎉 БАЗОВЫЕ КОНТЕЙНЕРЫ РАБОТАЮТ! 🎉🎉
          Проверьте Ubuntu тест для полного подтверждения
          
          {% else %}
          💔 Проблемы остались - проверьте логи:
          - journalctl -u slurmd -f
          - /var/log/slurm/slurmd.log  
          - /var/log/syslog (prolog/epilog логи)
          
          {% endif %}
          ===============================================================================

# =============================================================================
# ФИНАЛЬНАЯ ИНФОРМАЦИЯ
# =============================================================================

- name: "📋 ФИНАЛЬНАЯ ИНФОРМАЦИЯ"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "🎯 Итоги финального исправления"
      debug:
        msg: |
          ===============================================================================
          🎯 ФИНАЛЬНОЕ ИСПРАВЛЕНИЕ ENROOT ЗАВЕРШЕНО
          ===============================================================================
          
          ✅ ПРИМЕНЕНО ПРОДАКШН РЕШЕНИЕ:
          
          📝 1. Правильная enroot.conf с пользователь-специфичными путями:
             - ENROOT_RUNTIME_PATH /run/enroot/user-$(id -u)
             - ENROOT_CACHE_PATH /var/lib/enroot-cache/group-$(id -g)  
             - ENROOT_DATA_PATH /tmp/enroot-data/user-$(id -u)
             - ENROOT_REMAP_ROOT n (не делать пользователя root'ом!)
          
          📁 2. Prolog скрипт (как в DeepOps):
             - Создает пользовательские директории
             - Устанавливает правильные права (0700 для пользователя)
             - Запускается ПЕРЕД каждой задачей
          
          🧹 3. Epilog скрипт (как в DeepOps):
             - Очищает пользовательские данные
             - Оставляет групповой cache нетронутым
             - Запускается ПОСЛЕ каждой задачи
          
          ⚙️  4. Интеграция со Slurm:
             - Prolog=/etc/slurm/prolog.sh
             - Epilog=/etc/slurm/epilog.sh
             - Автоматический запуск для всех задач
          
          🎯 РЕЗУЛЬТАТ:
          Контейнеры работают для ОБЫЧНЫХ пользователей без root привилегий!
          Основано на реальной продакшн конфигурации + лучшие практики NVIDIA.
          
          ===============================================================================