---
# Развертывание Slurm кластера

- name: "Build Slurm"
  hosts: slurm-master
  become: true
  roles:
    - slurm_build

- name: "Setup Slurm Master"
  hosts: slurm-master
  become: true
  roles:
    - slurm_master

- name: "Setup Slurm Login"
  hosts: slurm-login
  become: true
  roles:
    - slurm_login

- name: "Setup Slurm Compute"
  hosts: slurm-node
  become: true
  roles:
    - slurm_compute
