
---
# playbooks/slurm_cluster.yml
# Развертывание Slurm кластера

- name: "Build Slurm"
  hosts: slurm_master
  become: true
  roles:
    - slurm_build

- name: "Setup Slurm Master"
  hosts: slurm_master
  become: true
  roles:
    - slurm_master

- name: "Setup Slurm Login"
  hosts: slurm_login
  become: true
  roles:
    - slurm_login

- name: "Setup Slurm Compute"
  hosts: slurm_compute  # ИСПРАВЛЕНО: было slurm-node
  become: true
  roles:
    - slurm_compute