# playbooks/test_containers.yml
---
# Тестирование контейнерной поддержки Enroot + Pyxis

- name: "🧪 Тестирование Enroot + Pyxis"
  hosts: slurm_cluster
  become: true
  gather_facts: true
  
  tasks:
    - name: "📋 Информация о тестировании"
      debug:
        msg: |
          🧪 ТЕСТИРОВАНИЕ КОНТЕЙНЕРНОЙ ПОДДЕРЖКИ
          =============================================
          🔧 Проверяем: Enroot, Pyxis, SPANK плагин
          🎮 GPU: {{ ansible_processor_vcpus }} CPU, {{ (ansible_memtotal_mb/1024)|round(1) }}GB RAM
          📍 Узел: {{ inventory_hostname }}
          =============================================

    # =======================================================================
    # ПРОВЕРКА УСТАНОВКИ КОМПОНЕНТОВ
    # =======================================================================
    
    - name: "[TEST] Проверка версии Enroot"
      command: enroot version
      register: enroot_version_test
      changed_when: false
      failed_when: false
      tags: verify
    
    - name: "[TEST] Проверка SPANK плагина Pyxis"
      stat:
        path: /usr/local/pyxis/lib/slurm/spank_pyxis.so
      register: pyxis_spank_test
      tags: verify
    
    - name: "[TEST] Проверка конфигурации plugstack.conf"
      command: grep -q "spank_pyxis.so" /etc/slurm/plugstack.conf
      register: plugstack_test
      changed_when: false
      failed_when: false
      tags: verify
    
    # =======================================================================
    # ТЕСТ ОСНОВНОЙ ФУНКЦИОНАЛЬНОСТИ
    # =======================================================================
    
    - name: "[TEST] Базовый тест Enroot"
      shell: |
        # Тест создания простого контейнера
        timeout 60 enroot import docker://hello-world 2>/dev/null || echo "Import test completed"
        enroot list 2>/dev/null || echo "List test completed"
      register: enroot_basic_test
      changed_when: false
      failed_when: false
      become_user: root
      tags: test_basic
    
    - name: "[TEST] Проверка GPU доступности"
      shell: |
        if command -v nvidia-smi >/dev/null 2>&1; then
          echo "GPU_COUNT=$(nvidia-smi -L | wc -l)"
          echo "GPU_DRIVER=$(nvidia-smi --query-gpu=driver_version --format=csv,noheader,nounits | head -1)"
          echo "GPU_STATUS=available"
        else
          echo "GPU_STATUS=unavailable"
        fi
      register: gpu_availability_test
      changed_when: false
      tags: test_gpu
    
    # =======================================================================
    # ТЕСТ ИНТЕГРАЦИИ С SLURM (только на compute узлах)
    # =======================================================================
    
    - name: "[TEST] Тест интеграции Pyxis с Slurm"
      shell: |
        # Проверяем что SPANK плагин загружается
        if command -v slurmd >/dev/null 2>&1; then
          slurmd -V 2>&1 | grep -i spank || echo "SPANK info not available"
          echo "SLURM_VERSION=$(slurmd -V | head -1)"
        else
          echo "SLURMD_STATUS=not_available"
        fi
      register: slurm_integration_test
      changed_when: false
      when: inventory_hostname in groups['slurm_compute']
      tags: test_integration
    
    # =======================================================================
    # ТЕСТ ПРАВ И ДИРЕКТОРИЙ
    # =======================================================================
    
    - name: "[TEST] Проверка прав доступа к директориям"
      shell: |
        echo "=== ДИРЕКТОРИИ ENROOT ==="
        ls -la /var/lib/enroot/ 2>/dev/null || echo "/var/lib/enroot недоступна"
        ls -la /var/cache/enroot/ 2>/dev/null || echo "/var/cache/enroot недоступна"
        ls -la /run/enroot/ 2>/dev/null || echo "/run/enroot недоступна"
        
        echo "=== PROLOG/EPILOG СКРИПТЫ ==="
        ls -la /etc/slurm/prolog.d/ 2>/dev/null || echo "prolog.d недоступна"
        ls -la /etc/slurm/epilog.d/ 2>/dev/null || echo "epilog.d недоступна"
        
        echo "=== BIND MOUNTS ==="
        mount | grep -E "(home|sw)" || echo "NFS mounts не найдены"
      register: permissions_test
      changed_when: false
      tags: test_permissions

# ==========================================================================
# ОТЧЕТ О РЕЗУЛЬТАТАХ ТЕСТИРОВАНИЯ
# ==========================================================================

- name: "📊 Отчет о тестировании контейнеров"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "🎯 Результаты тестирования Enroot + Pyxis"
      debug:
        msg: |
          ==========================================
          🧪 РЕЗУЛЬТАТЫ ТЕСТИРОВАНИЯ КОНТЕЙНЕРОВ
          ==========================================
          
          {% for host in groups['slurm_cluster'] %}
          🖥️ {{ host }}:
          {% set host_vars = hostvars[host] %}
          📦 Enroot: {{ host_vars.enroot_version_test.stdout | default('ошибка') }}
          🔌 Pyxis SPANK: {{ host_vars.pyxis_spank_test.stat.exists | default(false) | ternary('✅ найден', '❌ не найден') }}
          ⚙️ Plugstack: {{ host_vars.plugstack_test.rc | default(1) == 0 | ternary('✅ настроен', '❌ не настроен') }}
          
          {% if host_vars.gpu_availability_test.stdout is defined %}
          🎮 GPU: {{ host_vars.gpu_availability_test.stdout | regex_search('GPU_STATUS=(.+)', '\\1') | first | default('неизвестно') }}
          {% endif %}
          
          {% if host in groups['slurm_compute'] and host_vars.slurm_integration_test.stdout is defined %}
          🔗 Slurm: {{ host_vars.slurm_integration_test.stdout | regex_search('SLURM_VERSION=(.+)', '\\1') | first | default('недоступен') }}
          {% endif %}
          
          {% endfor %}
          
          ==========================================
          🚀 КОМАНДЫ ДЛЯ ТЕСТИРОВАНИЯ:
          ==========================================
          
          # Простой контейнер:
          srun --container-image=docker://hello-world
          
          # Интерактивная сессия:
          srun --pty --container-image=docker://ubuntu:20.04 /bin/bash
          
          # С GPU (если доступны):
          srun --gpus=1 --container-image=nvcr.io/nvidia/pytorch:latest nvidia-smi
          
          # Batch задача:
          sbatch --wrap="echo 'Container test'" --container-image=docker://ubuntu:20.04
          
          ==========================================
      run_once: true