---
# Тестовый playbook для роли common

- name: "Тестирование роли common"
  hosts: slurm_cluster
  become: true
  gather_facts: true
  
  pre_tasks:
    - name: "Информация о тестировании"
      debug:
        msg: |
          🧪 Тестируем роль common на кластере
          🎯 Узлы: {{ groups['slurm_cluster'] }}
          📊 Всего узлов: {{ groups['slurm_cluster'] | length }}

  roles:
    - common

  post_tasks:
    - name: "Проверка результатов"
      debug:
        msg: |
          ✅ Роль common протестирована на {{ inventory_hostname }}
          🔧 Проверьте работу MUNGE: systemctl status munge
          📁 Проверьте NFS монтирование: df -h | grep nfs
          👤 Проверьте пользователя slurm: id slurm