# playbooks/test_slurm_compute.yml
---
# =============================================================================
# ТЕСТИРОВАНИЕ РОЛИ SLURM_COMPUTE
# =============================================================================

- name: "🧪 Тестирование роли slurm_compute"
  hosts: slurm_compute
  become: yes
  gather_facts: yes
  
  vars:
    # Переменные для тестирования
    slurm_install_prefix: "/usr/local/slurm"
    slurm_config_dir: "/etc/slurm"
    slurm_log_dir: "/var/log/slurm"
    gpu_detection_enabled: true
    
  pre_tasks:
    - name: "[TEST] Информация о тестировании"
      debug:
        msg: |
          🎯 Тестируем роль slurm_compute на {{ inventory_hostname }}
          📦 Slurm установлен: {{ slurm_install_prefix }}
          🔗 Master узел: {{ groups['slurm_master'][0] }}
          🖥️  GPU тест: включен
      tags: always

    - name: "[TEST] Проверка предварительных условий"
      stat:
        path: "{{ item }}"
      register: prereq_check
      loop:
        - "{{ slurm_install_prefix }}/sbin/slurmd"
        - "/etc/munge/munge.key"
        - "/sw/config/slurm.conf"
      tags: pre-check
      
    - name: "[TEST] Результаты проверки предварительных условий"
      debug:
        msg: |
          📋 Предварительные условия:
          {% for item in prereq_check.results %}
          {{ item.item }}: {{ item.stat.exists | ternary('✅ найден', '❌ отсутствует') }}
          {% endfor %}
      tags: pre-check

  tasks:
    - name: "[TEST] Выполнение роли slurm_compute"
      include_role:
        name: slurm_compute
      tags: role

  post_tasks:
    - name: "[TEST] Проверка результатов развертывания"
      systemd:
        name: slurmd
      register: slurmd_status
      tags: verify

    - name: "[TEST] Проверка созданных файлов"
      stat:
        path: "{{ item }}"
      register: files_check
      loop:
        - "/etc/systemd/system/slurmd.service"
        - "{{ slurm_config_dir }}/slurm.conf"
        - "{{ slurm_config_dir }}/gres.conf"
        - "/usr/local/bin/slurm_health_check.sh"
        - "/usr/sbin/slurmd"
      tags: verify

    - name: "[TEST] Результаты проверки файлов"
      debug:
        msg: |
          📁 Созданные файлы:
          {% for item in files_check.results %}
          {{ item.item }}: {{ item.stat.exists | ternary('✅ создан', '❌ отсутствует') }}
          {% endfor %}
      tags: verify

    - name: "[TEST] Проверка логов slurmd"
      shell: |
        if systemctl is-active slurmd >/dev/null 2>&1; then
          echo "🎛️ slurmd: АКТИВЕН"
          echo "📝 Последние строки лога:"
          tail -3 {{ slurm_log_dir }}/slurmd.log 2>/dev/null || echo "Логи пока недоступны"
        else
          echo "🎛️ slurmd: НЕАКТИВЕН"
          echo "📝 Ошибки из journalctl:"
          journalctl -u slurmd -n 3 --no-pager
        fi
      register: slurmd_logs
      changed_when: false
      tags: verify

    - name: "[TEST] Тест подключения к мастеру (с мастера)"
      shell: /usr/bin/scontrol ping
      register: master_ping
      delegate_to: "{{ groups['slurm_master'][0] }}"
      run_once: true
      changed_when: false
      failed_when: false
      tags: verify

    - name: "[TEST] Статус узлов в кластере (с мастера)"
      shell: /usr/bin/sinfo -N
      register: cluster_status
      delegate_to: "{{ groups['slurm_master'][0] }}"
      run_once: true
      changed_when: false
      failed_when: false
      tags: verify

    - name: "[TEST] Финальный отчет"
      debug:
        msg: |
          📊 РЕЗУЛЬТАТЫ ТЕСТИРОВАНИЯ РОЛИ SLURM_COMPUTE
          
          🎛️ Статус сервиса slurmd:
          {{ slurmd_logs.stdout }}
          
          🔗 Подключение к мастеру:
          {{ master_ping.stdout | default('Ошибка подключения') }}
          
          📋 Статус кластера:
          {{ cluster_status.stdout | default('Информация недоступна') }}
          
          {% if slurmd_status.status.ActiveState == 'active' %}
          ✅ ТЕСТ ПРОЙДЕН: slurmd работает на {{ inventory_hostname }}
          {% else %}
          ❌ ТЕСТ НЕ ПРОЙДЕН: slurmd не активен
          {% endif %}
          
          🔧 Следующие шаги:
          1. Проверьте статус: systemctl status slurmd
          2. На мастере запустите: sinfo
          3. Узлы должны перейти из unknown* в idle
      run_once: true
      tags: verify